[[files]]
source = "package.json"
target = "package.json"
required_context = ["project_slug"]

[[files]]
source = "tsconfig.json"
target = "tsconfig.json"

[[files]]
source = "server.ts"
target = "src/server.ts"
required_context = ["project_name"]
