[[files]]
source = "pom.xml"
target = "pom.xml"

[[files]]
source = "Application.java"
target = "src/main/java/com/{{ project_slug }}/Application.java"

[[files]]
source = "HealthController.java"
target = "src/main/java/com/{{ project_slug }}/api/HealthController.java"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
