[[files]]
source = "Cargo.toml"
required_context = ["project_slug"]
target = "Cargo.toml"

[[files]]
source = "main.rs"
target = "src/main.rs"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
