[[files]]
source = "package.js.json"
target = "apps/backend/package.json"
required_context = ["project_slug"]
exclude_features = ["typescript"]

[[files]]
source = "package.ts.json"
target = "apps/backend/package.json"
required_context = ["project_slug"]
include_features = ["typescript"]

[[files]]
source = "tsconfig.json"
target = "apps/backend/tsconfig.json"
include_features = ["typescript"]

[[files]]
source = "server.js"
target = "apps/backend/src/server.js"
required_context = ["project_name"]
exclude_features = ["typescript"]

[[files]]
source = "server.ts"
target = "apps/backend/src/server.ts"
required_context = ["project_name"]
include_features = ["typescript"]

[[files]]
source = "app.js"
target = "apps/backend/src/lib/app.js"
required_context = ["project_name"]
exclude_features = ["typescript"]

[[files]]
source = "app.ts"
target = "apps/backend/src/lib/app.ts"
required_context = ["project_name"]
include_features = ["typescript"]
