[[files]]
source = "package.ts.json"
target = "apps/backend/package.json"
required_context = ["project_slug"]
include_features = ["typescript"]

[[files]]
source = "package.js.json"
target = "apps/backend/package.json"
required_context = ["project_slug"]
exclude_features = ["typescript"]

[[files]]
source = "tsconfig.json"
target = "apps/backend/tsconfig.json"
include_features = ["typescript"]

[[files]]
source = "server.js"
target = "apps/backend/src/server.js"
exclude_features = ["typescript"]

[[files]]
source = "server.ts"
target = "apps/backend/src/server.ts"
include_features = ["typescript"]

[[files]]
source = "app.js"
target = "apps/backend/src/app.js"
exclude_features = ["typescript"]

[[files]]
source = "app.ts"
target = "apps/backend/src/app.ts"
include_features = ["typescript"]

[[files]]
source = "vitest.config.ts"
target = "apps/backend/vitest.config.ts"
include_features = ["vitest"]

[[files]]
source = "app.spec.ts"
target = "apps/backend/src/app.spec.ts"
include_features = ["vitest"]

[[files]]
source = "schema.prisma"
target = "apps/backend/prisma/schema.prisma"
include_features = ["prisma"]

[[files]]
source = "prisma.ts"
target = "apps/backend/src/lib/prisma.ts"
include_features = ["prisma"]
