[[files]]
source = "contracts.package.json"
target = "packages/contracts/package.json"
required_context = ["project_slug"]

[[files]]
source = "contracts.index.js"
target = "packages/contracts/src/index.js"
exclude_features = ["typescript"]

[[files]]
source = "contracts.index.ts"
target = "packages/contracts/src/index.ts"
include_features = ["typescript"]

[[files]]
source = "config.README.md"
target = "packages/config/README.md"
