[[files]]
source = "manage.py"
target = "apps/backend/manage.py"

[[files]]
source = "main.py"
target = "apps/backend/src/main.py"

[[files]]
source = "requirements.txt"
target = "apps/backend/requirements.txt"

[[files]]
source = "Dockerfile"
target = "apps/backend/Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = "apps/backend/.dockerignore"
include_features = ["docker"]
