[package]
name = "mg-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "mg"
path = "src/main.rs"

[dependencies]
mg-core = { path = "../mg-core" }
mg-store = { path = "../mg-store" }
mg-resolver = { path = "../mg-resolver" }
mg-lockfile = { path = "../mg-lockfile" }
mg-installer = { path = "../mg-installer" }
mg-linker = { path = "../mg-linker" }
mg-registry = { path = "../mg-registry" }
mg-workspace = { path = "../mg-workspace" }
mg-plugins = { path = "../mg-plugins" }
mg-scaffold = { path = "../mg-scaffold" }
thiserror.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
napi.workspace = true
napi-derive.workspace = true
clap.workspace = true
clap_complete.workspace = true
url.workspace = true
colored.workspace = true
indicatif.workspace = true
console.workspace = true
tracing.workspace = true
once_cell.workspace = true
dirs.workspace = true
serde_yaml.workspace = true
semver.workspace = true
hex.workspace = true
base64.workspace = true
flate2.workspace = true
rusqlite.workspace = true
toml.workspace = true
reqwest.workspace = true

[dev-dependencies]
proptest.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
tempfile = "3.8"