[[files]]
source = "composer.json"
required_context = ["project_slug"]
target = "apps/backend/composer.json"

[[files]]
source = "index.php"
target = "apps/backend/public/index.php"

[[files]]
source = "Dockerfile"
target = "apps/backend/Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = "apps/backend/.dockerignore"
include_features = ["docker"]
