load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "megagate_fetcher",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        ":megagate_types",
        ":megagate_extractor",
        "@crates_io//async_trait",
        "@crates_io//bytes",
        "@crates_io//dashmap",
        "@crates_io//governor",
        "@crates_io//reqwest",
        "@crates_io//serde_json",
        "@crates_io//tokio",
    ],
)

rust_test(
    name = "megagate_fetcher_test",
    crate = ":megagate_fetcher",
)