[package]
name = "megagate-fetcher"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = false

[dependencies]
megagate-types = { path = "../megagate-types" }
megagate-extractor = { path = "../megagate-extractor" }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
serde_json = { workspace = true }
governor = "0.6"
semver = { workspace = true }