[build]
# Use native linker

[alias]
b = "build --release"
c = "check"
t = "test"
tc = "test --lib"
ti = "test --test integration"
f = "fmt --all"
fc = "fmt --all -- --check"
l = "clippy --workspace -- -D warnings"
d = "doc --workspace --no-deps --open"
bench = "bench --workspace"