FROM php:8.3-cli
RUN apt-get update && apt-get install -y libpq-dev libonig-dev && docker-php-ext-install pdo_pgsql mbstring
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY composer.json ./
RUN composer install --no-interaction
COPY . .
EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
