//! `adapters/bun.rs` — Bun Optimizer Adapter
//! `adapters/bun.rs` — Adapter tối ưu hóa Bun

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::HardwareInfo;
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct BunAdapter;

impl OptimizerAdapter for BunAdapter {
    fn name(&self) -> &'static str {
        "Bun"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Bun)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let concurrency = hw.cpu_cores.map(|cores| cores.saturating_mul(10));
        let concurrency_line = concurrency
            .map(|value| format!("BUN_CONFIG_MAX_HTTP_REQUESTS={value}\n"))
            .unwrap_or_else(|| "# CPU count unknown; keep Bun's runtime default.\n".to_string());
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/bun_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Bun ({:?})\n\
                 BUN_RUNTIME_TRANSPILER_CACHE_PATH=.mgc-optimizer/.bun-cache\n\
                 BUN_INSTALL_BIN=./node_modules/.bin\n\
                 {concurrency_line}",
                hw.profile,
            ),
            description: concurrency
                .map(|value| format!("Bun cache & HTTP concurrency ({value})"))
                .unwrap_or_else(|| "Bun cache; HTTP concurrency unchanged".to_string()),
        });

        files
    }
}
