//! `adapters/bun.rs` — Bun Optimizer Adapter
//! `adapters/bun.rs` — Adapter tối ưu hóa Bun

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::HardwareInfo;
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct BunAdapter;

impl OptimizerAdapter for BunAdapter {
    fn name(&self) -> &'static str {
        "Bun"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Bun)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/bun_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Bun ({:?})\n\
                 BUN_RUNTIME_TRANSPILER_CACHE_PATH=.mgc-optimizer/.bun-cache\n\
                 BUN_INSTALL_BIN=./node_modules/.bin\n\
                 BUN_CONFIG_MAX_HTTP_REQUESTS={}\n",
                hw.profile,
                hw.cpu_cores * 10
            ),
            description: format!("Bun cache & HTTP concurrency ({})", hw.cpu_cores * 10),
        });

        files
    }
}
