//! `adapters/bun.rs` — Bun Optimizer Adapter
//! `adapters/bun.rs` — Adapter tối ưu hóa Bun

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct BunAdapter;

impl OptimizerAdapter for BunAdapter {
    fn name(&self) -> &'static str {
        "Bun"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Bun)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let heap_size = match hw.profile {
            SystemProfile::HighPerformance => 8192,
            SystemProfile::Standard => 4096,
            SystemProfile::Constrained => 2048,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/bun_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Bun ({:?})\n\
                 BUN_RUNTIME_TRANSPILER_CACHE_PATH=.mgc-optimizer/.bun-cache\n\
                 BUN_INSTALL_BIN=./node_modules/.bin\n\
                 BUN_JSC_maxHeapSize={heap_size}m\n\
                 BUN_CONFIG_MAX_HTTP_REQUESTS={}\n",
                hw.profile,
                hw.cpu_cores * 10
            ),
            description: format!(
                "Bun JSC heap ({heap_size}MB) & HTTP concurrency ({})",
                hw.cpu_cores * 10
            ),
        });

        files
    }
}
