//! `adapters/candle.rs` — Rust/Candle Optimizer Adapter
//! `adapters/candle.rs` — Adapter tối ưu hóa Rust/Candle

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct CandleAdapter;

impl OptimizerAdapter for CandleAdapter {
    fn name(&self) -> &'static str {
        "Rust/Candle"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::RustCandle)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        // Candle uses Rayon for CPU parallelism — Candle dùng Rayon cho song song CPU
        let rayon_threads = hw.cpu_cores;

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/candle_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Rust/Candle ({:?})\n\
                 RAYON_NUM_THREADS={rayon_threads}\n\
                 RUST_BACKTRACE=1\n\
                 CANDLE_ENABLE_CUDA=auto\n\
                 CANDLE_USE_MKLDNN=1\n",
                hw.profile
            ),
            description: format!(
                "Candle Rayon thread pool ({rayon_threads} threads) & CUDA auto-detection"
            ),
        });

        let (opt_level, lto) = match hw.profile {
            SystemProfile::HighPerformance => ("3", "thin"),
            SystemProfile::Standard => ("2", "false"),
            SystemProfile::Constrained => ("1", "false"),
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/candle_cargo.toml".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Rust/Candle ({:?})\n\
                 [profile.release]\n\
                 opt-level = {opt_level}\n\
                 lto = \"{lto}\"\n\
                 codegen-units = 1\n\
                 panic = \"abort\"\n\n\
                 [build]\n\
                 jobs = {rayon_threads}\n",
                hw.profile
            ),
            description: format!(
                "Cargo build profile for Candle AI workloads (opt-level={opt_level}, lto={lto})"
            ),
        });

        files
    }
}
