//! `adapters/deno.rs` — Deno Optimizer Adapter
//! `adapters/deno.rs` — Adapter tối ưu hóa Deno

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct DenoAdapter;

impl OptimizerAdapter for DenoAdapter {
    fn name(&self) -> &'static str {
        "Deno"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Deno)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let v8_flags = match hw.profile {
            SystemProfile::HighPerformance => "--max-old-space-size=8192",
            SystemProfile::Standard => "--max-old-space-size=4096",
            SystemProfile::Constrained => "--max-old-space-size=2048",
        };

        let jobs_line = hw
            .cpu_cores
            .map(|cores| format!("DENO_JOBS={cores}\n"))
            .unwrap_or_else(|| "# CPU count unknown; keep Deno's runtime default.\n".to_string());
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/deno_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Deno ({:?})\n\
                 DENO_V8_FLAGS=\"{v8_flags}\"\n\
                 {jobs_line}\
                 NO_COLOR=1\n",
                hw.profile
            ),
            description: hw
                .cpu_cores
                .map(|cores| format!("Deno V8 flags & parallel jobs ({cores})"))
                .unwrap_or_else(|| "Deno V8 flags; parallelism unchanged".to_string()),
        });

        files
    }
}
