//! `adapters/flutter.rs` — Flutter Optimizer Adapter
//! `adapters/flutter.rs` — Adapter tối ưu hóa Flutter

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct FlutterAdapter;

impl OptimizerAdapter for FlutterAdapter {
    fn name(&self) -> &'static str {
        "Flutter"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Flutter)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let build_mode = match hw.profile {
            SystemProfile::HighPerformance => "release",
            SystemProfile::Standard => "profile",
            SystemProfile::Constrained => "debug",
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/flutter_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Flutter ({:?})\n\
                 FLUTTER_BUILD_MODE={build_mode}\n\
                 DART_VM_OPTIONS=\"--old_gen_heap_size={}\"\n\
                 FLUTTER_CACHE_DIR=.mgc-optimizer/.flutter-cache\n\
                 PUB_CACHE=.mgc-optimizer/.pub-cache\n",
                hw.profile,
                (hw.total_memory_gb * 256).min(4096)
            ),
            description: format!("Flutter build mode ({build_mode}) & Dart VM heap optimization"),
        });

        files
    }
}
