//! `adapters/flutter.rs` — Flutter Optimizer Adapter
//! `adapters/flutter.rs` — Adapter tối ưu hóa Flutter

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct FlutterAdapter;

impl OptimizerAdapter for FlutterAdapter {
    fn name(&self) -> &'static str {
        "Flutter"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::Flutter)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let build_mode = match hw.profile {
            SystemProfile::HighPerformance => "release",
            SystemProfile::Standard => "profile",
            SystemProfile::Constrained => "debug",
        };

        // Heap size derives from measured RAM only — unknown RAM omits
        // the knob instead of fabricating it (P0: no memory-derived
        // tuning from Unknown).
        // (Heap từ RAM đo được — unknown thì bỏ knob, không bịa.)
        let heap_line = hw
            .total_memory_gb
            .map(|gb| {
                format!(
                    "DART_VM_OPTIONS=\"--old_gen_heap_size={}\"\n",
                    (gb * 256).min(4096)
                )
            })
            .unwrap_or_default();
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/flutter_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Flutter ({:?})\n\
                 FLUTTER_BUILD_MODE={build_mode}\n\
                 {heap_line}\
                 FLUTTER_CACHE_DIR=.mgc-optimizer/.flutter-cache\n\
                 PUB_CACHE=.mgc-optimizer/.pub-cache\n",
                hw.profile,
            ),
            description: format!("Flutter build mode ({build_mode}) & Dart VM heap optimization"),
        });

        files
    }
}
