//! `adapters/go_ai.rs` — Go AI (TensorFlow/ONNX) Optimizer Adapter
//! `adapters/go_ai.rs` — Adapter tối ưu hóa Go AI (TensorFlow/ONNX)

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct GoAiAdapter;

impl OptimizerAdapter for GoAiAdapter {
    fn name(&self) -> &'static str {
        "Go/TensorFlow"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::GoTensorFlow)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let gomaxprocs = hw.cpu_cores;
        let gogc = match hw.profile {
            SystemProfile::HighPerformance => 100, // default GC
            SystemProfile::Standard => 150,        // less frequent GC
            SystemProfile::Constrained => 200,     // minimal GC overhead
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/go_ai_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Go AI ({:?})\n\
                 GOMAXPROCS={gomaxprocs}\n\
                 GOGC={gogc}\n\
                 GODEBUG=gctrace=0\n\
                 TF_CPP_MIN_LOG_LEVEL=2\n\
                 ONNXRUNTIME_LOG_LEVEL=2\n",
                hw.profile
            ),
            description: format!(
                "Go runtime (GOMAXPROCS={gomaxprocs}, GOGC={gogc}) & TensorFlow/ONNX logging"
            ),
        });

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/go_build.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Go AI build ({:?})\n\
                 # CGO required for TensorFlow/ONNX bindings\n\
                 CGO_ENABLED=1\n\
                 GO111MODULE=on\n\
                 # Module proxy: respects user settings via env override\n\
                 # Default: official Go proxy with direct fallback\n\
                 # Override via: export GOPROXY=<your-proxy>\n\
                 GOPROXY=${{GOPROXY:-https://proxy.golang.org,direct}}\n\
                 # Module cache: uses MagiCore shared cache structure\n\
                 # Override via: export GOMODCACHE=<your-path>\n\
                 GOMODCACHE=${{GOMODCACHE:-.mgc-optimizer/.go-mod-cache}}\n",
                hw.profile
            ),
            description: "Go build flags for CGO-dependent AI libraries (TensorFlow/ONNX)"
                .to_string(),
        });

        files
    }
}
