//! `adapters/go_lib.rs` — Go Library Optimizer Adapter
//! `adapters/go_lib.rs` — Adapter tối ưu hóa thư viện Go

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct GoLibAdapter;

impl OptimizerAdapter for GoLibAdapter {
    fn name(&self) -> &'static str {
        "Go Library"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::GoLib)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let gomaxprocs = hw.cpu_cores;
        let gogc = match hw.profile {
            SystemProfile::HighPerformance => 100,
            SystemProfile::Standard => 150,
            SystemProfile::Constrained => 200,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/go_lib_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Go Library ({:?})\n\
                 # Go runtime tuning\n\
                 GOMAXPROCS={gomaxprocs}\n\
                 GOGC={gogc}\n\
                 GO111MODULE=on\n\
                 # Module proxy: respects user settings via env override\n\
                 # Default: official Go proxy with direct fallback\n\
                 # Override via: export GOPROXY=<your-proxy>\n\
                 GOPROXY=${{GOPROXY:-https://proxy.golang.org,direct}}\n\
                 # Module cache: uses MagiCore shared cache structure\n\
                 # Override via: export GOMODCACHE=<your-path>\n\
                 GOMODCACHE=${{GOMODCACHE:-.mgc-optimizer/.go-mod-cache}}\n\
                 GOPRIVATE=\n",
                hw.profile
            ),
            description: format!(
                "Go runtime (GOMAXPROCS={gomaxprocs}, GOGC={gogc}) & module cache"
            ),
        });

        files
    }
}
