//! `adapters/node.rs` — Node.js/V8 Optimizer Adapter
//! `adapters/node.rs` — Adapter tối ưu hóa Node.js/V8

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct NodeJsAdapter;

impl OptimizerAdapter for NodeJsAdapter {
    fn name(&self) -> &'static str {
        "Node.js"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::NodeJs { .. })
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let max_old_space = match hw.profile {
            SystemProfile::HighPerformance => 8192,
            SystemProfile::Standard => 4096,
            SystemProfile::Constrained => 2048,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/nodejs_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Node.js ({:?})\n\
                 NODE_OPTIONS=\"--max-old-space-size={max_old_space} --enable-source-maps\"\n\
                 UV_THREADPOOL_SIZE={}\n\
                 VITE_ESBUILD_TARGET=esnext\n\
                 NEXT_TELEMETRY_DISABLED=1\n",
                hw.profile,
                hw.cpu_cores.max(4)
            ),
            description: format!(
                "Node.js V8 Heap ({max_old_space}MB) & async I/O worker threads ({})",
                hw.cpu_cores.max(4)
            ),
        });

        files
    }
}
