//! `adapters/node.rs` — Node.js/V8 Optimizer Adapter
//! `adapters/node.rs` — Adapter tối ưu hóa Node.js/V8

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct NodeJsAdapter;

impl OptimizerAdapter for NodeJsAdapter {
    fn name(&self) -> &'static str {
        "Node.js"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::NodeJs { .. })
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let max_old_space = match hw.profile {
            SystemProfile::HighPerformance => 8192,
            SystemProfile::Standard => 4096,
            SystemProfile::Constrained => 2048,
        };

        let worker_pool = hw
            .cpu_cores
            .map(|cores| format!("UV_THREADPOOL_SIZE={}\n", cores.max(4)))
            .unwrap_or_else(|| "# CPU count unknown; keep libuv's runtime default.\n".to_string());
        let worker_description = hw
            .cpu_cores
            .map(|cores| format!("async I/O worker pool ({})", cores.max(4)))
            .unwrap_or_else(|| "async I/O worker pool unchanged".to_string());
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/node_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Node.js ({:?})\n\
                 NODE_OPTIONS=\"--max-old-space-size={max_old_space} --enable-source-maps\"\n\
                 {worker_pool}\
                 VITE_ESBUILD_TARGET=esnext\n\
                 NEXT_TELEMETRY_DISABLED=1\n",
                hw.profile,
            ),
            description: format!("Node.js V8 Heap ({max_old_space}MB) & {worker_description}"),
        });

        files
    }
}
