//! `adapters/python_lib.rs` — Python Library Optimizer Adapter
//! `adapters/python_lib.rs` — Adapter tối ưu hóa thư viện Python

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct PythonLibAdapter;

impl OptimizerAdapter for PythonLibAdapter {
    fn name(&self) -> &'static str {
        "Python Library"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::PythonLib)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let workers = hw.cpu_cores.map(|cores| cores.max(2));
        let workers_line = workers
            .map(|count| format!("UV_CONCURRENT_DOWNLOADS={count}\n"))
            .unwrap_or_else(|| "# CPU count unknown; keep uv's runtime default.\n".to_string());
        let cache_size = match hw.profile {
            SystemProfile::HighPerformance => 512,
            SystemProfile::Standard => 256,
            SystemProfile::Constrained => 128,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/python_lib_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Python Library ({:?})\n\
                 PYTHONOPTIMIZE=1\n\
                 PYTHONDONTWRITEBYTECODE=1\n\
                 PYTHONUNBUFFERED=1\n\
                 UV_CACHE_DIR=.mgc-optimizer/.uv-cache\n\
                 PIP_CACHE_DIR=.mgc-optimizer/.pip-cache\n\
                 {workers_line}\
                 PY_COMPILE_CACHE_SIZE={cache_size}\n",
                hw.profile
            ),
            description: format!(
                "Python optimization flags & UV/pip cache (cache size={cache_size}MB)"
            ),
        });

        files
    }
}
