//! `adapters/python_lib.rs` — Python Library Optimizer Adapter
//! `adapters/python_lib.rs` — Adapter tối ưu hóa thư viện Python

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct PythonLibAdapter;

impl OptimizerAdapter for PythonLibAdapter {
    fn name(&self) -> &'static str {
        "Python Library"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::PythonLib)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let workers = hw.cpu_cores.max(2);
        let cache_size = match hw.profile {
            SystemProfile::HighPerformance => 512,
            SystemProfile::Standard => 256,
            SystemProfile::Constrained => 128,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/python_lib_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Python Library ({:?})\n\
                 PYTHONOPTIMIZE=1\n\
                 PYTHONDONTWRITEBYTECODE=1\n\
                 PYTHONUNBUFFERED=1\n\
                 UV_CACHE_DIR=.mgc-optimizer/.uv-cache\n\
                 PIP_CACHE_DIR=.mgc-optimizer/.pip-cache\n\
                 UV_CONCURRENT_DOWNLOADS={}\n\
                 PY_COMPILE_CACHE_SIZE={cache_size}\n",
                hw.profile, workers
            ),
            description: format!(
                "Python optimization flags & UV/pip cache (cache size={cache_size}MB)"
            ),
        });

        files
    }
}
