//! `adapters/pytorch.rs` — PyTorch Optimizer Adapter
//! `adapters/pytorch.rs` — Adapter tối ưu hóa PyTorch

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::HardwareInfo;
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct PyTorchAdapter;

impl OptimizerAdapter for PyTorchAdapter {
    fn name(&self) -> &'static str {
        "PyTorch"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::PythonPyTorch)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];
        let threads = hw.cpu_cores.max(1);

        // Standard PyTorch environment variables (documented & verifiable) — biến môi trường PyTorch chuẩn (đã chứng minh)
        // No unproven claims (ultra-compression, token pruning, etc.) — không có claims chưa chứng minh
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch ({:?})\n\
                 # Standard PyTorch threading environment variables\n\
                 OMP_NUM_THREADS={threads}\n\
                 MKL_NUM_THREADS={threads}\n\
                 TORCH_NUM_THREADS={threads}\n\
                 TOKENIZERS_PARALLELISM=true\n\
                 # CUDA memory allocator tuning (PyTorch documented)\n\
                 PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512\n",
                hw.profile
            ),
            description: format!(
                "PyTorch compute thread pool ({threads} threads) & CUDA memory tuning"
            ),
        });

        // Docker resource limits (standard container optimization) — giới hạn tài nguyên Docker (tối ưu container chuẩn)
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_docker.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch Container ({:?})\n\
                 # Reserve 10% CPU overhead & 2GB RAM for OS\n\
                 CONTAINER_CPUS={:.1}\n\
                 CONTAINER_MEMORY={}g\n",
                hw.profile,
                (hw.cpu_cores as f64) * 0.9,
                (hw.total_memory_gb.saturating_sub(2)).max(2)
            ),
            description: "Docker CPU/Memory limits for PyTorch workloads".to_string(),
        });

        files
    }
}
