//! `adapters/pytorch.rs` — PyTorch Optimizer Adapter
//! `adapters/pytorch.rs` — Adapter tối ưu hóa PyTorch

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::HardwareInfo;
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct PyTorchAdapter;

impl OptimizerAdapter for PyTorchAdapter {
    fn name(&self) -> &'static str {
        "PyTorch"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::PythonPyTorch)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];
        let threads = hw.cpu_cores.max(1);

        // Standard PyTorch environment variables (documented & verifiable) — biến môi trường PyTorch chuẩn (đã chứng minh)
        // No unproven claims (ultra-compression, token pruning, etc.) — không có claims chưa chứng minh
        // Accelerator lines are CONDITIONED on measured GPUs: the CUDA
        // allocator knob only exists where an NVIDIA card was detected,
        // the MPS fallback only where an Apple GPU was detected.
        // Emitting them unconditionally would fake hardware that is not
        // there. (Dòng accelerator có điều kiện theo GPU đo được.)
        let mut accelerator = String::new();
        if hw.has_gpu_vendor("nvidia") {
            accelerator.push_str(
                "# CUDA memory allocator tuning, NVIDIA GPU detected (PyTorch documented)\n\
                 PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512\n",
            );
        }
        if hw.has_gpu_vendor("apple") {
            accelerator.push_str(
                "# Apple GPU detected: allow MPS-op fallback to CPU (PyTorch documented)\n\
                 PYTORCH_ENABLE_MPS_FALLBACK=1\n",
            );
        }
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch ({:?})\n\
                 # Standard PyTorch threading environment variables\n\
                 OMP_NUM_THREADS={threads}\n\
                 MKL_NUM_THREADS={threads}\n\
                 TORCH_NUM_THREADS={threads}\n\
                 TOKENIZERS_PARALLELISM=true\n\
                 {accelerator}",
                hw.profile
            ),
            description: format!(
                "PyTorch compute thread pool ({threads} threads) & GPU-conditioned accelerator env"
            ),
        });

        // Docker resource limits (standard container optimization) — giới hạn tài nguyên Docker (tối ưu container chuẩn)
        // Memory limit derives from measured RAM only — unknown RAM omits
        // the knob (an unconstrained container beats a fabricated limit).
        // (Giới hạn RAM từ RAM đo được — unknown thì bỏ knob.)
        let memory_line = hw
            .total_memory_gb
            .map(|gb| format!("CONTAINER_MEMORY={}g\n", gb.saturating_sub(2).max(2)))
            .unwrap_or_default();
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_docker.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch Container ({:?})\n\
                 # Reserve 10% CPU overhead & 2GB RAM for OS\n\
                 CONTAINER_CPUS={:.1}\n\
                 {memory_line}",
                hw.profile,
                (hw.cpu_cores as f64) * 0.9,
            ),
            description: "Docker CPU/Memory limits for PyTorch workloads".to_string(),
        });

        files
    }
}
