//! `adapters/pytorch.rs` — PyTorch Optimizer Adapter
//! `adapters/pytorch.rs` — Adapter tối ưu hóa PyTorch

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::HardwareInfo;
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct PyTorchAdapter;

impl OptimizerAdapter for PyTorchAdapter {
    fn name(&self) -> &'static str {
        "PyTorch"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::PythonPyTorch)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];
        let threads = hw.cpu_cores;
        let thread_env = threads
            .map(|count| {
                format!(
                    "OMP_NUM_THREADS={count}\nMKL_NUM_THREADS={count}\nTORCH_NUM_THREADS={count}\n"
                )
            })
            .unwrap_or_else(|| {
                "# CPU count unknown; keep framework thread-pool defaults.\n".to_string()
            });

        // Standard PyTorch environment variables (documented & verifiable) — biến môi trường PyTorch chuẩn (đã chứng minh)
        // No unproven claims (ultra-compression, token pruning, etc.) — không có claims chưa chứng minh
        // Accelerator lines are CONDITIONED on measured GPUs: the CUDA
        // allocator knob only exists where an NVIDIA card was detected,
        // the MPS fallback only where an Apple GPU was detected.
        // Emitting them unconditionally would fake hardware that is not
        // there. (Dòng accelerator có điều kiện theo GPU đo được.)
        let mut accelerator = String::new();
        if hw.has_gpu_vendor("nvidia") == Some(true) {
            accelerator.push_str(
                "# CUDA memory allocator tuning, NVIDIA GPU detected (PyTorch documented)\n\
                 PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512\n",
            );
        }
        if hw.has_gpu_vendor("apple") == Some(true) {
            accelerator.push_str(
                "# Apple GPU detected: allow MPS-op fallback to CPU (PyTorch documented)\n\
                 PYTORCH_ENABLE_MPS_FALLBACK=1\n",
            );
        }
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_runtime.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch ({:?})\n\
                 # Standard PyTorch threading environment variables\n\
                 {thread_env}\
                 TOKENIZERS_PARALLELISM=true\n\
                 {accelerator}",
                hw.profile
            ),
            description: format!(
                "PyTorch compute thread pool ({}) & GPU-conditioned accelerator env",
                threads
                    .map(|count| count.to_string())
                    .unwrap_or_else(|| "default".to_string())
            ),
        });

        // Docker resource limits (standard container optimization) — giới hạn tài nguyên Docker (tối ưu container chuẩn)
        // Memory limit derives from measured RAM only — unknown RAM omits
        // the knob (an unconstrained container beats a fabricated limit).
        // (Giới hạn RAM từ RAM đo được — unknown thì bỏ knob.)
        let memory_line = hw
            .total_memory_gb
            .map(|gb| format!("CONTAINER_MEMORY={}g\n", gb.saturating_sub(2).max(2)))
            .unwrap_or_default();
        let cpu_limit_line = hw
            .cpu_cores
            .map(|cores| format!("CONTAINER_CPUS={:.1}\n", (cores as f64) * 0.9))
            .unwrap_or_else(|| {
                "# CPU count unknown; do not synthesize a container limit.\n".to_string()
            });
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/pytorch_docker.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for PyTorch Container ({:?})\n\
                 # Reserve 10% CPU overhead & 2GB RAM for OS\n\
                 {cpu_limit_line}\
                 {memory_line}",
                hw.profile,
            ),
            description: if hw.cpu_cores.is_some() || hw.total_memory_gb.is_some() {
                "Docker limits derived from measured CPU/RAM values".to_string()
            } else {
                "Docker limit file contains no synthesized CPU/RAM bounds".to_string()
            },
        });

        files
    }
}
