//! `adapters/react_native.rs` — React Native Optimizer Adapter
//! `adapters/react_native.rs` — Adapter tối ưu hóa React Native

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct ReactNativeAdapter;

impl OptimizerAdapter for ReactNativeAdapter {
    fn name(&self) -> &'static str {
        "React Native"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::ReactNative)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let max_old_space = match hw.profile {
            SystemProfile::HighPerformance => 8192,
            SystemProfile::Standard => 4096,
            SystemProfile::Constrained => 2048,
        };

        let metro_workers = hw.cpu_cores.max(2);

        // RULE §13 compliant port: 5314 is permutation of {4,3,1,5} — cổng tuân thủ RULE §13
        // User can override via environment: RCT_METRO_PORT — user có thể override qua biến môi trường
        // Default 5314 avoids common conflicts (5000, 8080, 8081) — mặc định 5314 tránh conflict phổ biến
        let default_metro_port = 5314;

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/react_native_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for React Native ({:?})\n\
                 # Metro bundler port (RULE §13 compliant: 5314 is permutation of 4,3,1,5)\n\
                 # Override via: export RCT_METRO_PORT=<your-port>\n\
                 NODE_OPTIONS=\"--max-old-space-size={max_old_space}\"\n\
                 METRO_CACHE=.mgc-optimizer/.metro-cache\n\
                 METRO_MAX_WORKERS={metro_workers}\n\
                 RCT_METRO_PORT=${{RCT_METRO_PORT:-{default_metro_port}}}\n\
                 REACT_NATIVE_BUILD_OUTPUT=.mgc-optimizer/build\n",
                hw.profile
            ),
            description: format!(
                "React Native Metro bundler ({metro_workers} workers, port {default_metro_port}) & V8 heap ({max_old_space}MB)"
            ),
        });

        files
    }
}
