//! `adapters/rust_lib.rs` — Rust Library Optimizer Adapter
//! `adapters/rust_lib.rs` — Adapter tối ưu hóa thư viện Rust

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct RustLibAdapter;

impl OptimizerAdapter for RustLibAdapter {
    fn name(&self) -> &'static str {
        "Rust Library"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(
            runtime,
            DetectedRuntime::RustLib | DetectedRuntime::RustNative
        )
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let (opt_level, codegen_units, lto) = match hw.profile {
            SystemProfile::HighPerformance => ("3", "16", "thin"),
            SystemProfile::Standard => ("2", "8", "false"),
            SystemProfile::Constrained => ("1", "4", "false"),
        };

        let lld_flag = if hw.os == "macos" {
            "# Native Apple Clang linker"
        } else {
            "rustflags = [\"-C\", \"linker=clang\", \"-C\", \"link-arg=-fuse-ld=lld\", \"-C\", \"target-cpu=native\"]"
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/rust_cargo_profile.toml".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Rust Library ({:?})\n\
                 [build]\n\
                 jobs = {}\n\
                 {lld_flag}\n\n\
                 [profile.dev]\n\
                 opt-level = {opt_level}\n\
                 codegen-units = {codegen_units}\n\
                 debug = 1\n\n\
                 [profile.release]\n\
                 opt-level = 3\n\
                 lto = \"{lto}\"\n\
                 codegen-units = 1\n\
                 panic = \"abort\"\n",
                hw.profile, hw.cpu_cores
            ),
            description: format!(
                "Cargo parallel build ({} jobs) & dev/release profile",
                hw.cpu_cores
            ),
        });

        files
    }
}
