//! `adapters/typescript_lib.rs` — TypeScript Library Optimizer Adapter
//! `adapters/typescript_lib.rs` — Adapter tối ưu hóa thư viện TypeScript

use super::OptimizerAdapter;
use crate::commands::optimizer::detect::{HardwareInfo, SystemProfile};
use crate::commands::optimizer::generators::OptimizedConfigFile;
use crate::commands::optimizer::runtime_detect::DetectedRuntime;

pub struct TypeScriptLibAdapter;

impl OptimizerAdapter for TypeScriptLibAdapter {
    fn name(&self) -> &'static str {
        "TypeScript Library"
    }

    fn matches(&self, runtime: &DetectedRuntime) -> bool {
        matches!(runtime, DetectedRuntime::TypeScriptLib)
    }

    fn generate(&self, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
        let mut files = vec![];

        let max_old_space = match hw.profile {
            SystemProfile::HighPerformance => 4096,
            SystemProfile::Standard => 2048,
            SystemProfile::Constrained => 1024,
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/typescript_lib_env.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for TypeScript Library ({:?})\n\
                 NODE_OPTIONS=\"--max-old-space-size={max_old_space}\"\n\
                 TS_NODE_TRANSPILE_ONLY=true\n\
                 TS_NODE_FILES=true\n\
                 TSC_COMPILE_ON_ERROR=false\n",
                hw.profile
            ),
            description: format!("TypeScript lib V8 heap ({max_old_space}MB) & compilation flags"),
        });

        files
    }
}
