[package]
name = "megagate-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = false

[[bin]]
name = "megagate"
path = "src/main.rs"

[dependencies]
megagate-core = { path = "../megagate-core" }
megagate-types = { path = "../megagate-types" }
clap = { workspace = true }
colored = { workspace = true }
indicatif = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }