[[files]]
source = "package.ts.json"
target = "apps/frontend/package.json"
required_context = ["project_slug"]
include_features = ["typescript"]

[[files]]
source = "angular.json"
target = "apps/frontend/angular.json"
required_context = ["project_slug"]

[[files]]
source = "tsconfig.json"
target = "apps/frontend/tsconfig.json"
include_features = ["typescript"]

[[files]]
source = "tsconfig.app.json"
target = "apps/frontend/tsconfig.app.json"
include_features = ["typescript"]

[[files]]
source = "src/index.html"
target = "apps/frontend/src/index.html"
required_context = ["project_name"]

[[files]]
source = "src/main.ts"
target = "apps/frontend/src/main.ts"
include_features = ["typescript"]

[[files]]
source = "src/styles.css"
target = "apps/frontend/src/styles.css"

[[files]]
source = "src/app/app.config.ts"
target = "apps/frontend/src/app/app.config.ts"
include_features = ["typescript"]

[[files]]
source = "src/app/app.routes.ts"
target = "apps/frontend/src/app/app.routes.ts"
include_features = ["typescript"]

[[files]]
source = "src/app/app.component.ts"
target = "apps/frontend/src/app/app.component.ts"
required_context = ["project_name"]
include_features = ["typescript"]

[[files]]
source = "src/public/.gitkeep"
target = "apps/frontend/src/public/.gitkeep"
