[[files]]
source = "main.py"
target = "src/main.py"

[[files]]
source = "requirements.txt"
target = "requirements.txt"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
