#![cfg(test)]
#![allow(clippy::unwrap_used)]
//! Tests for dispatch engine recursive and audit-strict logic

use super::*;

#[test]
fn audit_strict_rejects_materializing_install_commands() {
    let install = Commands::Install {
        packages: vec![],
        frozen: false,
        ignore_scripts: false,
        allow_scripts: false,
        prefer_dedupe: false,
        repair: false,
        dry_run: false,
        offline: false,
    };
    assert!(reject_unsupported_audit_strict(&install).is_ok());

    let add = Commands::AddWeb {
        packages: vec!["zod".into()],
        dev: false,
        exact: false,
        optional: false,
        peer: false,
        no_save: false,
        no_install: false,
        global: false,
    };
    assert!(reject_unsupported_audit_strict(&add).is_ok());
}

#[test]
fn audit_strict_allows_audit_and_manifest_only_mutation() {
    assert!(reject_unsupported_audit_strict(&Commands::Audit { fix: false }).is_ok());

    let add = Commands::AddWeb {
        packages: vec!["zod".into()],
        dev: false,
        exact: false,
        optional: false,
        peer: false,
        no_save: false,
        no_install: true,
        global: false,
    };
    assert!(reject_unsupported_audit_strict(&add).is_ok());
}

#[test]
fn recursive_is_rejected_for_unsupported_commands() {
    // Init không có trong recursive_supported → phải bị reject.
    let err = reject_unsupported_recursive(Some(&Commands::Init {
        template: None,
        signature: None,
    }))
    .unwrap_err();
    assert!(
        err.to_string()
            .contains("--recursive is not implemented for 'init' yet"),
        "unexpected error: {err}"
    );
}

#[test]
fn recursive_supported_includes_build_run_audit_outdated_dev() {
    // T4: xác nhận các lệnh mới được mở rộng recursive support
    assert!(recursive_supported(&Commands::Build { target: None }));
    assert!(recursive_supported(&Commands::Audit { fix: false }));
    assert!(recursive_supported(&Commands::Outdated { json: false }));
    assert!(recursive_supported(&Commands::Dev {
        host: None,
        port: None,
        clear: false,
    }));
}

#[test]
fn recursive_supported_includes_install_and_add() {
    // Existing commands vẫn supported sau T4
    assert!(recursive_supported(&Commands::Install {
        packages: vec![],
        frozen: false,
        ignore_scripts: false,
        allow_scripts: false,
        prefer_dedupe: false,
        repair: false,
        dry_run: false,
        offline: false,
    }));
    assert!(recursive_supported(&Commands::List));
}

#[test]
fn read_core_marker_parses_plain_and_comment() {
    // T4: đọc .mgc.core marker với/không có comment
    let dir = std::env::temp_dir().join(format!("mgc_test_marker_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    // Plain value
    std::fs::write(dir.join(".mgc.core"), "web\n").unwrap();
    assert_eq!(read_core_marker(&dir), Some("web".to_string()));

    // With comment
    std::fs::write(dir.join(".mgc.core"), "ai # generated by mgc init\n").unwrap();
    assert_eq!(read_core_marker(&dir), Some("ai".to_string()));

    // Empty → None
    std::fs::write(dir.join(".mgc.core"), "# just a comment\n").unwrap();
    assert_eq!(read_core_marker(&dir), None);

    // Missing file → None
    std::fs::remove_file(dir.join(".mgc.core")).unwrap();
    assert_eq!(read_core_marker(&dir), None);

    std::fs::remove_dir(&dir).ok();
}
