//! Unit tests for MagiCore Optimizer Engine

use super::detect::*;
use super::generators::*;
use std::fs;
use tempfile::tempdir;

#[test]
fn test_hardware_detect_returns_valid_info() {
    let hw = HardwareInfo::detect();
    assert!(hw.cpu_cores > 0);
    assert!(!hw.arch.is_empty());
    assert!(!hw.os.is_empty());
    assert!(hw.total_memory_gb > 0);
}

#[test]
fn test_generate_optimizations_for_web_core() {
    let hw = HardwareInfo {
        cpu_cores: 8,
        arch: "aarch64".to_string(),
        os: "macos".to_string(),
        total_memory_gb: 16,
        profile: SystemProfile::HighPerformance,
    };

    let files = generate_optimizations_for_core("web", &hw);
    // Profile JSON + Web Env
    assert_eq!(files.len(), 2);
    assert!(files[0].relative_path.contains("profile.json"));
    assert!(files[1].content.contains("max-old-space-size=8192"));
    assert!(files[1].content.contains("UV_THREADPOOL_SIZE=8"));
}

#[test]
fn test_generate_optimizations_for_game_core() {
    let hw = HardwareInfo {
        cpu_cores: 12,
        arch: "x86_64".to_string(),
        os: "linux".to_string(),
        total_memory_gb: 32,
        profile: SystemProfile::HighPerformance,
    };

    let files = generate_optimizations_for_core("game", &hw);
    assert_eq!(files.len(), 2);
    assert!(files[1].content.contains("jobs = 12"));
    assert!(files[1].content.contains("opt-level = 3"));
}

#[test]
fn test_hash_guard_prevents_overwriting_user_custom_file() {
    let dir = tempdir().unwrap();
    let root = dir.path();

    let opt_file = OptimizedConfigFile {
        relative_path: ".mgc-optimizer/test.env".to_string(),
        content: "# Generated by MagiCore Optimizer\nKEY=VALUE\n".to_string(),
        description: "Test env".to_string(),
    };

    // Lần 1: Tạo mới thành công
    let ok = apply_optimized_file(root, &opt_file, false).unwrap();
    assert!(ok);

    // User sửa tay file (mất comment Generated by)
    let file_path = root.join(".mgc-optimizer/test.env");
    fs::write(&file_path, "USER_CUSTOM_KEY=CUSTOM_VALUE\n").unwrap();

    // Lần 2 (force=false): Phải từ chối ghi đè để bảo vệ chỉnh sửa của user
    let ok2 = apply_optimized_file(root, &opt_file, false).unwrap();
    assert!(!ok2);
    let content = fs::read_to_string(&file_path).unwrap();
    assert_eq!(content, "USER_CUSTOM_KEY=CUSTOM_VALUE\n");

    // Lần 3 (force=true): Bắt buộc ghi đè
    let ok3 = apply_optimized_file(root, &opt_file, true).unwrap();
    assert!(ok3);
    let content_after = fs::read_to_string(&file_path).unwrap();
    assert!(content_after.contains("Generated by MagiCore Optimizer"));
}
