//! Unit tests for MagiCore Optimizer Engine

use super::detect::*;
use super::generators::*;
use std::fs;
use tempfile::tempdir;

#[test]
fn test_hardware_detect_returns_valid_info() {
    let hw = HardwareInfo::detect();
    assert!(hw.cpu_cores > 0);
    assert!(!hw.arch.is_empty());
    assert!(!hw.os.is_empty());
    assert!(hw.total_memory_gb > 0);
}

#[test]
fn test_generate_optimizations_for_web_core() {
    let dir = tempdir().unwrap();
    let project_root = dir.path();

    // Create package.json to trigger Node.js detection
    fs::write(project_root.join("package.json"), "{}").unwrap();

    let hw = HardwareInfo {
        cpu_cores: 8,
        arch: "aarch64".to_string(),
        os: "macos".to_string(),
        total_memory_gb: 16,
        profile: SystemProfile::HighPerformance,
    };

    let files = generate_optimizations_for_core("web", &hw, project_root);
    // Profile JSON + Node.js Env (from adapter)
    assert!(files.len() >= 2);
    assert!(files[0].relative_path.contains("profile.json"));
    // Node.js adapter should generate config
    assert!(
        files
            .iter()
            .any(|f| f.content.contains("max-old-space-size"))
    );
}

#[test]
fn test_generate_optimizations_for_game_core() {
    let dir = tempdir().unwrap();
    let project_root = dir.path();

    // Create Cargo.toml to trigger Rust detection
    fs::write(
        project_root.join("Cargo.toml"),
        "[package]\nname = \"test\"\n",
    )
    .unwrap();

    let hw = HardwareInfo {
        cpu_cores: 12,
        arch: "x86_64".to_string(),
        os: "linux".to_string(),
        total_memory_gb: 32,
        profile: SystemProfile::HighPerformance,
    };

    let files = generate_optimizations_for_core("game", &hw, project_root);
    assert!(files.len() >= 2);
    // Rust lib adapter should generate Cargo profile config
    assert!(files.iter().any(|f| f.content.contains("jobs")));
}

#[test]
fn test_profile_for_unknown_ram_degrades_to_constrained() {
    // Unknown RAM must never tune from a guessed size: even a 64-core
    // machine degrades to Constrained when memory cannot be measured.
    // (RAM unknown không bao giờ tuning từ số đoán: máy 64 core cũng hạ
    // về Constrained khi không đo được RAM.)
    assert_eq!(
        HardwareInfo::profile_for(64, None),
        SystemProfile::Constrained
    );
    assert_eq!(
        HardwareInfo::profile_for(8, Some(16)),
        SystemProfile::HighPerformance
    );
    assert_eq!(
        HardwareInfo::profile_for(4, Some(8)),
        SystemProfile::Standard
    );
    assert_eq!(
        HardwareInfo::profile_for(2, Some(4)),
        SystemProfile::Constrained
    );
}

#[test]
fn test_unknown_ram_skips_memory_derived_configs() {
    // total_memory_gb == 0 is the unknown sentinel: only the honest
    // manifest may be emitted, never adapter files with degenerate
    // memory-derived values (e.g. a 0MB Dart heap).
    // (total_memory_gb == 0 là sentinel unknown: chỉ manifest trung thực
    // được xuất, không bao giờ file adapter với giá trị suy biến.)
    let dir = tempdir().unwrap();
    let project_root = dir.path();
    fs::write(project_root.join("package.json"), "{}").unwrap();

    let hw = HardwareInfo {
        cpu_cores: 8,
        arch: "x86_64".to_string(),
        os: "linux".to_string(),
        total_memory_gb: 0,
        profile: SystemProfile::Constrained,
    };

    let files = generate_optimizations_for_core("web", &hw, project_root);
    assert_eq!(files.len(), 1);
    assert!(files[0].relative_path.contains("profile.json"));
}

#[test]
fn test_optimize_project_without_runtime_fails_closed() {
    // No detectable runtime is NOT a success: automation must observe an
    // error, never Ok(()) for work that never happened.
    // (Không có runtime không phải thành công: automation phải thấy lỗi.)
    let dir = tempdir().unwrap();
    let result = super::optimize_project(dir.path(), "web", false);
    assert!(
        result.is_err(),
        "optimize with no detectable runtime must fail closed"
    );
}

#[test]
fn test_hash_guard_prevents_overwriting_user_custom_file() {
    let dir = tempdir().unwrap();
    let root = dir.path();

    let opt_file = OptimizedConfigFile {
        relative_path: ".mgc-optimizer/test.env".to_string(),
        content: "# Generated by MagiCore Optimizer\nKEY=VALUE\n".to_string(),
        description: "Test env".to_string(),
    };

    // Lần 1: Tạo mới thành công
    let ok = apply_optimized_file(root, &opt_file, false).unwrap();
    assert!(ok);

    // User sửa tay file (mất comment Generated by)
    let file_path = root.join(".mgc-optimizer/test.env");
    fs::write(&file_path, "USER_CUSTOM_KEY=CUSTOM_VALUE\n").unwrap();

    // Lần 2 (force=false): Phải từ chối ghi đè để bảo vệ chỉnh sửa của user
    let ok2 = apply_optimized_file(root, &opt_file, false).unwrap();
    assert!(!ok2);
    let content = fs::read_to_string(&file_path).unwrap();
    assert_eq!(content, "USER_CUSTOM_KEY=CUSTOM_VALUE\n");

    // Lần 3 (force=true): Bắt buộc ghi đè
    let ok3 = apply_optimized_file(root, &opt_file, true).unwrap();
    assert!(ok3);
    let content_after = fs::read_to_string(&file_path).unwrap();
    assert!(content_after.contains("Generated by MagiCore Optimizer"));
}
