[[files]]
source = "Cargo.toml"
required_context = ["project_slug"]
target = "apps/backend/Cargo.toml"

[[files]]
source = "main.rs"
target = "apps/backend/src/main.rs"

[[files]]
source = "Dockerfile"
target = "apps/backend/Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = "apps/backend/.dockerignore"
include_features = ["docker"]
