//! `scanners/dart.rs` — Flutter/Dart CVE scanner via OSV.dev
//! (`Pub` ecosystem (OSV name, capitalized — verified live) — P2 2026-09-10 matrix row "App Flutter/Dart pub
//! dependencies + OSV/SBOM mapping").
//!
//! pubspec.lock pins are extracted (yaml lock — the `packages:` map
//! with `version:` fields, `sdks:` and hosted/git/sdk sources
//! distinguished) and queried against OSV. This REPLACES the honest
//! unsupported stub for flutter when pubspec.lock exists; a project
//! without pubspec.lock stays unsupported with real remediation.
//!
//! Scanner CVE Flutter/Dart qua OSV.dev (ecosystem `pub`): trích ghim
//! từ pubspec.lock (bản yaml — map `packages:` với field `version:`,
//! phân biệt nguồn hosted/git/sdk) rồi truy vấn OSV. Thay stub
//! unsupported trung thực khi có pubspec.lock; thiếu lockfile thì giữ
//! unsupported kèm hướng dẫn thật.

use crate::scanners::osv::{OsvPin, audit_osv_pins};
use mgc_types::adapter::{AuditReport, ScannerStatus};
use mgc_types::{MgError, MgResult};
use std::path::Path;

/// pubspec.lock is a small, stable yaml subset — parse the
/// `packages:` map with a line-oriented reader (no yaml dependency:
/// the file shape is generated by pub and flat two-level keys).
/// pubspec.lock là tập con yaml nhỏ ổn định — đọc map `packages:` theo
/// dòng (không cần dependency yaml: file do pub sinh, khóa phẳng 2 cấp).
pub fn read_pubspec_lock(raw: &str) -> MgResult<(Vec<OsvPin>, Vec<String>)> {
    let mut pins = Vec::new();
    let mut skipped = Vec::new();
    let mut in_packages = false;
    let mut current_name: Option<String> = None;

    for line in raw.lines() {
        let trimmed_end = line.trim_end();
        // Top-level key: column 0.
        // Key cấp gốc: cột 0.
        if !line.starts_with(' ') && !trimmed_end.is_empty() {
            in_packages = trimmed_end == "packages:";
            current_name = None;
            continue;
        }
        if !in_packages {
            continue;
        }
        let entry = trimmed_end.trim_start();

        // "  <name>:" starts a package block.
        // "  <name>:" bắt đầu block package.
        if entry.ends_with(':')
            && !entry.starts_with("version:")
            && !entry.starts_with("source:")
            && !entry.starts_with("description:")
            && !entry.starts_with("sha256:")
            && !entry.starts_with("url:")
            && !entry.starts_with("source-map:")
        {
            current_name = Some(entry[..entry.len() - 1].to_string());
            continue;
        }
        if let Some(rest) = entry.strip_prefix("version:") {
            let Some(name) = current_name.clone() else {
                continue;
            };
            let version = rest.trim().trim_matches('"');
            if version.is_empty() {
                skipped.push(format!("{name}: empty version pin"));
            } else {
                pins.push(OsvPin {
                    name,
                    version: version.to_string(),
                    ecosystem: "Pub",
                });
            }
        }
        if let Some(rest) = entry.strip_prefix("source:") {
            let source = rest.trim();
            if let Some(name) = current_name.clone()
                && source != "hosted"
                && !source.is_empty()
            {
                // git/path/sdk-sourced packages have no registry advisory
                // mapping — record the skip honestly.
                // Package nguồn git/path/sdk không có mapping advisory
                // registry — ghi skip trung thực.
                skipped.push(format!("{name}: source '{source}' has no advisory mapping"));
            }
        }
    }
    Ok((pins, skipped))
}

/// Flutter audit: pubspec.lock → OSV `Pub` ecosystem (OSV name, capitalized — verified live) queries. Without
/// pubspec.lock the old honest unsupported state stays (with real
/// remediation).
/// Audit Flutter: pubspec.lock → truy vấn OSV `pub`. Thiếu
/// pubspec.lock thì giữ trạng thái unsupported trung thực cũ (kèm
/// hướng dẫn thật).
pub async fn audit_flutter_osv(project_root: &Path) -> MgResult<AuditReport> {
    let lock_path = project_root.join("pubspec.lock");
    if !lock_path.is_file() {
        return Ok(AuditReport::unsupported_ecosystem(
            "flutter/dart (no pubspec.lock found — run flutter pub get first)",
        ));
    }
    let raw = std::fs::read_to_string(&lock_path)
        .map_err(|e| MgError::Other(format!("read pubspec.lock: {e}")))?;
    let (pins, skipped) = read_pubspec_lock(&raw)?;
    if pins.is_empty() && skipped.is_empty() {
        return Ok(AuditReport::clean(0));
    }
    if pins.is_empty() {
        return Ok(AuditReport {
            packages_audited: 0,
            vulnerability_count: 0,
            vulnerabilities: vec![],
            scanner_status: ScannerStatus::Partial {
                scanned: 0,
                skipped: skipped.len(),
                reasons: skipped,
            },
        });
    }
    let mut report = audit_osv_pins(&pins).await?;
    if !skipped.is_empty() {
        report.scanner_status = ScannerStatus::Partial {
            scanned: pins.len(),
            skipped: skipped.len(),
            reasons: skipped,
        };
    }
    Ok(report)
}
