FROM ruby:3.3-slim
RUN apt-get update && apt-get install -y libpq-dev build-essential
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
