use crate::dispatch::types::{detect_ecosystem, CoreCommand, DispatchCommand};
use crate::Commands;

/// Bare verb commands (install/add/remove/update/list) → CoreCommand theo --core hoặc detect_ecosystem.
pub fn bare_core_command(command: Commands, ecosystem: Option<String>) -> DispatchCommand {
    use DispatchCommand::Core as SomeCore;

    // Bare commands - use --core if provided, else auto-detect
    let ecosystem = ecosystem.or_else(|| detect_ecosystem().ok().flatten());

    match command {
        Commands::Install {
            packages,
            frozen,
            ignore_scripts,
            allow_scripts,
            prefer_dedupe,
            repair,
            dry_run,
        } => SomeCore(match ecosystem.as_deref() {
            Some("web") => CoreCommand::InstallWeb {
                packages,
                frozen,
                ignore_scripts,
                allow_scripts,
                prefer_dedupe,
                repair,
            },
            Some("game") => CoreCommand::InstallGame { packages },
            Some("ai") => CoreCommand::InstallAi { packages, dry_run },
            Some("clo") => CoreCommand::InstallClo { packages, dry_run },
            Some("cicd") => CoreCommand::InstallCicd { packages, dry_run },
            Some("iot") => CoreCommand::InstallIot { packages },
            Some("app") => CoreCommand::InstallApp { packages, dry_run },
            Some("lib") => CoreCommand::InstallLib { packages },
            _ => CoreCommand::InstallWeb {
                packages,
                frozen,
                ignore_scripts,
                allow_scripts,
                prefer_dedupe,
                repair,
            },
        }),
        Commands::Add {
            packages,
            dev,
            global,
            exact,
            optional,
            peer,
            no_save,
            no_install,
            ..
        } => SomeCore(match ecosystem.as_deref() {
            Some("web") => CoreCommand::AddWeb {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                install: !no_install,
                global,
            },
            Some("game") => CoreCommand::AddGame {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("ai") => CoreCommand::AddAi {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("clo") => CoreCommand::AddClo {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("cicd") => CoreCommand::AddCicd {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("iot") => CoreCommand::AddIot {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("app") => CoreCommand::AddApp {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            Some("hardware") => CoreCommand::AddHardware { packages },
            Some("lib") => CoreCommand::AddLib {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                global,
            },
            _ => CoreCommand::AddWeb {
                packages,
                dev,
                exact,
                optional,
                peer,
                no_save,
                install: !no_install,
                global,
            },
        }),
        Commands::Remove {
            packages,
            no_install,
        } => SomeCore(match ecosystem.as_deref() {
            Some("web") => CoreCommand::RemoveWeb {
                packages,
                install: !no_install,
            },
            Some("game") => CoreCommand::RemoveGame { packages },
            Some("ai") => CoreCommand::RemoveAi { packages },
            Some("clo") => CoreCommand::RemoveClo { packages },
            Some("cicd") => CoreCommand::RemoveCicd { packages },
            Some("iot") => CoreCommand::RemoveIot { packages },
            Some("app") => CoreCommand::RemoveApp { packages },
            Some("lib") => CoreCommand::RemoveLib { packages },
            _ => CoreCommand::RemoveWeb {
                packages,
                install: !no_install,
            },
        }),
        Commands::Update { packages, install } => SomeCore(match ecosystem.as_deref() {
            Some("web") => CoreCommand::UpdateWeb { packages, install },
            Some("game") => CoreCommand::UpdateGame { packages, install },
            Some("ai") => CoreCommand::UpdateAi { packages, install },
            Some("clo") => CoreCommand::UpdateClo { packages, install },
            Some("cicd") => CoreCommand::UpdateCicd { packages, install },
            Some("iot") => CoreCommand::UpdateIot { packages, install },
            Some("app") => CoreCommand::UpdateApp { packages, install },
            Some("lib") => CoreCommand::UpdateLib { packages, install },
            _ => CoreCommand::UpdateWeb { packages, install },
        }),
        Commands::List => SomeCore(match ecosystem.as_deref() {
            Some("web") => CoreCommand::ListWeb,
            Some("game") => CoreCommand::ListGame,
            Some("ai") => CoreCommand::ListAi,
            Some("clo") => CoreCommand::ListClo,
            Some("cicd") => CoreCommand::ListCicd,
            Some("iot") => CoreCommand::ListIot,
            Some("app") => CoreCommand::ListApp,
            Some("lib") => CoreCommand::ListLib,
            Some("hardware") => CoreCommand::ListHardware,
            _ => CoreCommand::ListWeb,
        }),
        _ => unreachable!("Unhandled command"),
    }
}
