[[files]]
source = "pom.xml"
required_context = ["project_slug"]
target = "pom.xml"

[[files]]
source = "Application.java"
required_context = ["project_slug"]
target = "src/main/java/com/app/Application.java"

[[files]]
source = "HealthController.java"
required_context = ["project_slug"]
target = "src/main/java/com/app/api/HealthController.java"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
