[[files]]
source = "composer.json"
target = "composer.json"
required_context = ["project_slug"]

[[files]]
source = "artisan"
target = "artisan"

[[files]]
source = "public/index.php"
target = "public/index.php"

[[files]]
source = "bootstrap/app.php"
target = "bootstrap/app.php"

[[files]]
source = "bootstrap/cache/.gitkeep"
target = "bootstrap/cache/.gitkeep"

[[files]]
source = "config/app.php"
target = "config/app.php"
required_context = ["project_name"]

[[files]]
source = "config/session.php"
target = "config/session.php"
required_context = ["project_name"]

[[files]]
source = "routes/web.php"
target = "routes/web.php"
required_context = ["project_name"]

[[files]]
source = "app/Http/Controllers/Controller.php"
target = "app/Http/Controllers/Controller.php"

[[files]]
source = "app/Http/Controllers/HealthController.php"
target = "app/Http/Controllers/HealthController.php"
required_context = ["project_name"]

[[files]]
source = "storage/framework/cache/.gitkeep"
target = "storage/framework/cache/.gitkeep"

[[files]]
source = "storage/framework/sessions/.gitkeep"
target = "storage/framework/sessions/.gitkeep"

[[files]]
source = "storage/framework/views/.gitkeep"
target = "storage/framework/views/.gitkeep"

[[files]]
source = "storage/logs/.gitkeep"
target = "storage/logs/.gitkeep"

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]
