[[files]]
source = "composer.json"
required_context = ["project_slug"]
target = "composer.json"

[[files]]
source = "index.php"
target = "public/index.php"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
