load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "megagate_security",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        ":megagate_types",
        "@crates_io//chrono",
        "@crates_io//hex",
        "@crates_io//regex",
        "@crates_io//ring",
        "@crates_io//serde",
        "@crates_io//serde_json",
        "@crates_io//thiserror",
        "@crates_io//tokio",
    ],
)

rust_test(
    name = "megagate_security_test",
    crate = ":megagate_security",
)