[package]
name = "megagate-linker"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = false

[dependencies]
megagate-types = { path = "../megagate-types" }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
dirs = { workspace = true }