FROM elixir:1.17-slim
RUN apt-get update && apt-get install -y build-essential git
WORKDIR /app
COPY mix.exs mix.lock ./
RUN mix do local.hex --force, local.rebar --force, deps.get
COPY . .
RUN mix compile
EXPOSE 4000
CMD ["mix", "phx.server"]
