app: mega-app

services:
  web:
    image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env:
      - DATABASE_URL

databases:
  - name: mega-db
    type: postgresql