//! mg docs — auto-generate CLI markdown từ clap schema (task #6, 21 §8)
//! (Không thêm dependency: render trực tiếp từ clap::Command tree.)

use anyhow::Result;
use clap::{Command, CommandFactory};
use std::path::PathBuf;

/// Render cây lệnh thành markdown đơn giản: heading per command + args
fn render(cmd: &Command, depth: usize) -> String {
    let mut out = String::new();
    let heading = "#".repeat(depth + 2);
    out.push_str(&format!("{heading} `{}`\n\n", cmd.get_name()));
    if let Some(about) = cmd.get_about() {
        out.push_str(&format!("{about}\n\n"));
    }
    for arg in cmd.get_arguments() {
        let flags = arg
            .get_long()
            .map(|l| format!("--{l}"))
            .or_else(|| arg.get_short().map(|s| format!("-{s}")));
        if let Some(f) = flags {
            let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
            out.push_str(&format!("- `{f}` — {help}\n"));
        }
    }
    for sub in cmd.get_subcommands() {
        out.push_str(&render(sub, depth + 1));
    }
    out
}

pub fn handle(output: Option<PathBuf>) -> Result<()> {
    let md = render(&crate::Cli::command(), 0);
    let header = "# MegaGate CLI\n\n> Auto-generated by `mg docs --generate` — đừng sửa tay, chạy lại lệnh.\n\n";
    let full = format!("{header}{md}");
    match output {
        Some(path) => {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&path, full)?;
            println!("docs written: {}", path.display());
        }
        None => print!("{full}"),
    }
    Ok(())
}