/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface NapiMegagate {
    napiMegagateInstall(projectDir: string, configJson?: string | undefined | null): Promise<string>;
    napiMegagateAdd(projectDir: string, packageSpec: string, dev: boolean): Promise<string>;
    napiMegagateUpdate(projectDir: string, packageName?: string | undefined | null): Promise<string>;
    napiMegagateRemove(projectDir: string, packageName: string): Promise<string>;
    napiMegagateList(projectDir: string, depth: number): Promise<string>;
    napiMegagateLockVerify(projectDir: string, configJson?: string | undefined | null): Promise<string>;
}

declare const native: NapiMegagate;
export default native;
