[package]
name = "megagate-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = true

[lib]
name = "megagate_core"
path = "src/lib.rs"

[dependencies]
megagate-types = { path = "../megagate-types" }
megagate-resolver = { path = "../megagate-resolver" }
megagate-linker = { path = "../megagate-linker" }
megagate-extractor = { path = "../megagate-extractor" }
megagate-fetcher = { path = "../megagate-fetcher" }
megagate-security = { path = "../megagate-security" }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }