load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "megagate_extractor",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        ":megagate_types",
        "@crates_io//async_tar",
        "@crates_io//async_trait",
        "@crates_io//flate2",
        "@crates_io//ring",
        "@crates_io//sha2",
        "@crates_io//tar",
        "@crates_io//tokio",
    ],
)

rust_test(
    name = "megagate_extractor_test",
    crate = ":megagate_extractor",
)