[package]
name = "megagate-resolver"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = false

[dependencies]
megagate-types = { path = "../megagate-types" }
megagate-security = { path = "../megagate-security" }
megagate-fetcher = { path = "../megagate-fetcher" }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
semver = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }