[[files]]
source = "package.json"
target = "package.json"
required_context = ["project_slug"]

[[files]]
source = "index.js.html"
target = "index.html"
required_context = ["project_name"]
exclude_features = ["typescript"]

[[files]]
source = "index.ts.html"
target = "index.html"
required_context = ["project_name"]
include_features = ["typescript"]

[[files]]
source = "jsconfig.json"
target = "jsconfig.json"
exclude_features = ["typescript"]

[[files]]
source = "tsconfig.json"
target = "tsconfig.json"
include_features = ["typescript"]

[[files]]
source = "vite-env.d.ts"
target = "src/vite-env.d.ts"
include_features = ["typescript"]

[[files]]
source = "vite.config.js"
target = "vite.config.js"
exclude_features = ["typescript"]

[[files]]
source = "vite.config.ts"
target = "vite.config.ts"
include_features = ["typescript"]

[[files]]
source = "main.js"
target = "src/main.js"
exclude_features = ["typescript"]

[[files]]
source = "main.ts"
target = "src/main.ts"
include_features = ["typescript"]

[[files]]
source = "App.vue"
target = "src/App.vue"

[[files]]
source = "components/AppShell.js.vue"
target = "src/components/AppShell.vue"
exclude_features = ["typescript"]

[[files]]
source = "components/AppShell.ts.vue"
target = "src/components/AppShell.vue"
include_features = ["typescript"]

[[files]]
source = "config/framework.js"
target = "src/config/framework.js"
exclude_features = ["typescript"]

[[files]]
source = "config/framework.ts"
target = "src/config/framework.ts"
include_features = ["typescript"]

[[files]]
source = "router/AppRouter.js.vue"
target = "src/router/AppRouter.vue"
exclude_features = ["typescript"]

[[files]]
source = "router/AppRouter.ts.vue"
target = "src/router/AppRouter.vue"
include_features = ["typescript"]
