[[files]]
source = "go.mod"
target = "apps/backend/go.mod"

[[files]]
source = "main.go"
target = "apps/backend/cmd/server/main.go"

[[files]]
source = "Dockerfile"
target = "apps/backend/Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = "apps/backend/.dockerignore"
include_features = ["docker"]
