[[files]]
source = "package.ts.json"
target = "apps/frontend/package.json"
required_context = ["project_slug"]
include_features = ["typescript"]

[[files]]
source = "package.js.json"
target = "apps/frontend/package.json"
required_context = ["project_slug"]
exclude_features = ["typescript"]

[[files]]
source = "vite.config.ts"
target = "apps/frontend/vite.config.ts"
include_features = ["typescript"]

[[files]]
source = "vite.config.js"
target = "apps/frontend/vite.config.js"
exclude_features = ["typescript"]

[[files]]
source = "tsconfig.json"
target = "apps/frontend/tsconfig.json"
include_features = ["typescript"]

[[files]]
source = "src/root.tsx"
target = "apps/frontend/src/root.tsx"
required_context = ["project_name"]
include_features = ["typescript"]

[[files]]
source = "src/root.jsx"
target = "apps/frontend/src/root.jsx"
required_context = ["project_name"]
exclude_features = ["typescript"]

[[files]]
source = "src/entry.ssr.tsx"
target = "apps/frontend/src/entry.ssr.tsx"
include_features = ["typescript"]

[[files]]
source = "src/entry.ssr.jsx"
target = "apps/frontend/src/entry.ssr.jsx"
exclude_features = ["typescript"]

[[files]]
source = "src/entry.dev.tsx"
target = "apps/frontend/src/entry.dev.tsx"
include_features = ["typescript"]

[[files]]
source = "src/entry.dev.jsx"
target = "apps/frontend/src/entry.dev.jsx"
exclude_features = ["typescript"]

[[files]]
source = "src/routes/index.tsx"
target = "apps/frontend/src/routes/index.tsx"
required_context = ["project_name"]
include_features = ["typescript"]

[[files]]
source = "src/routes/index.jsx"
target = "apps/frontend/src/routes/index.jsx"
required_context = ["project_name"]
exclude_features = ["typescript"]
