//! Compatibility exporters: canonical mgc.lock → ecosystem lockfile shapes.
//! Exporter tương thích: mgc.lock canonical → shape lockfile của hệ sinh thái.
//!
//! Phase 1 scope: SKELETON output — structurally correct conduits so legacy
//! toolchains can consume the canonical graph. They are NOT byte-perfect
//! toolchain lockfiles, never carry full toolchain metadata (checksums,
//! hashes), and never feed back into mgc.lock — mgc.lock stays the single
//! source of truth.
//! Phạm vi Phase 1: output SKELETON — đúng cấu trúc để toolchain cũ tiêu
//! thụ đồ thị canonical. KHÔNG phải lockfile byte-perfect của toolchain,
//! không mang đủ metadata của toolchain (checksum, hash) và không bao giờ
//! đổ ngược vào mgc.lock — mgc.lock vẫn là nguồn truth duy nhất.

use mgc_types::{MgError, MgResult};
use serde_json::{Map, Value, json};

use crate::ecosystem_tag::EcosystemTag;
use crate::schema::Lockfile;

/// Export destinations supported in Phase 1 — Đích export hỗ trợ ở Phase 1.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportTarget {
    /// Cargo.lock (TOML) for the cargo toolchain — Cargo.lock (TOML) cho toolchain cargo.
    CargoLock,
    /// requirements.txt (pip line format) — requirements.txt (định dạng dòng pip).
    RequirementsTxt,
    /// go.sum placeholder (comment skeleton) — go.sum placeholder (comment skeleton).
    GoSum,
    /// package-lock.json (npm lockfileVersion 3) — package-lock.json (npm lockfileVersion 3).
    PackageLock,
}

/// Export a canonical lock into the target ecosystem's lockfile shape.
/// Export lock canonical sang shape lockfile của hệ sinh thái đích.
///
/// Entries of a different ecosystem are filtered out by design — the target
/// toolchain must never see foreign pins. A matching entry with an empty
/// version fails closed. NOTE: MgError currently has no dedicated
/// `InvalidLock` variant, so an empty version maps to
/// `MgError::InvalidVersion` (deviation from the design sketch, recorded in
/// the change log; adding a variant to the shared error enum without a
/// compiler run would risk breaking exhaustive matches workspace-wide).
/// Entry khác ecosystem bị lọc bỏ theo thiết kế — toolchain đích không được
/// thấy pin lạ. Entry đúng ecosystem nhưng thiếu version thì fail-closed.
/// LƯU Ý: MgError hiện chưa có variant `InvalidLock` riêng nên version rỗng
/// ánh xạ sang `MgError::InvalidVersion` (deviation so với thiết kế, đã ghi
/// change log; thêm variant vào error enum dùng chung khi chưa chạy compiler
/// sẽ dễ làm vỡ các match exhaustive toàn workspace).
pub fn export_canonical(lock: &Lockfile, target: ExportTarget) -> MgResult<Vec<u8>> {
    match target {
        ExportTarget::CargoLock => export_cargo_lock(lock),
        ExportTarget::RequirementsTxt => export_requirements_txt(lock),
        ExportTarget::GoSum => export_go_sum(lock),
        ExportTarget::PackageLock => export_package_lock(lock),
    }
}

/// Header of skeleton text exports — rõ ràng đây là conduit, không phải lock gốc.
const TEXT_EXPORT_HEADER: &str = "# Generated by MagiCore (mgc.lock schema v3 export skeleton).\n\
     # Compatibility conduit only — mgc.lock remains the canonical lock.\n";

/// Cargo.lock skeleton: TOML header + one `[[package]]` per rust entry.
/// Cargo.lock skeleton: header TOML + một `[[package]]` mỗi entry rust.
fn export_cargo_lock(lock: &Lockfile) -> MgResult<Vec<u8>> {
    let mut out = String::from(TEXT_EXPORT_HEADER);
    // Current Cargo.lock on-disk format version — version format Cargo.lock hiện nay.
    out.push_str("version = 4\n");

    for pkg in lock
        .packages
        .iter()
        .filter(|p| p.ecosystem == EcosystemTag::Rust)
    {
        let version = require_version(pkg)?;
        out.push_str("\n[[package]]\n");
        out.push_str(&format!("name = \"{}\"\n", pkg.name));
        out.push_str(&format!("version = \"{version}\"\n"));
        if let Some(registry) = &pkg.registry {
            out.push_str(&format!("source = \"{}\"\n", cargo_source_url(registry)));
        }
    }

    Ok(out.into_bytes())
}

/// requirements.txt skeleton: one `name==version` pin per python entry.
/// requirements.txt skeleton: một pin `name==version` mỗi entry python.
fn export_requirements_txt(lock: &Lockfile) -> MgResult<Vec<u8>> {
    let mut out = String::from(TEXT_EXPORT_HEADER);
    for pkg in lock
        .packages
        .iter()
        .filter(|p| p.ecosystem == EcosystemTag::Python)
    {
        let version = require_version(pkg)?;
        out.push_str(&format!("{}=={version}\n", pkg.name));
    }
    Ok(out.into_bytes())
}

/// go.sum skeleton: comment-only placeholder — go regenerates the real
/// hashes from go.mod + module cache, so nothing non-comment is emitted.
/// go.sum skeleton: chỉ toàn comment — go sinh lại hash thật từ go.mod +
/// module cache, nên không xuất dòng nào ngoài comment.
fn export_go_sum(lock: &Lockfile) -> MgResult<Vec<u8>> {
    let mut out = String::from("# skeleton — go toolchain regenerates\n");
    for pkg in lock
        .packages
        .iter()
        .filter(|p| p.ecosystem == EcosystemTag::Go)
    {
        let version = require_version(pkg)?;
        // Still comment-only: module pins are informational, never parsed.
        // Vẫn chỉ là comment: pin module chỉ để tham chiếu, không được parse.
        out.push_str(&format!("# module {}@{version}\n", pkg.name));
    }
    Ok(out.into_bytes())
}

/// package-lock.json skeleton: lockfileVersion 3 + `packages` map with one
/// `node_modules/<name>` entry per web package.
/// package-lock.json skeleton: lockfileVersion 3 + map `packages` với một
/// entry `node_modules/<name>` mỗi package web.
fn export_package_lock(lock: &Lockfile) -> MgResult<Vec<u8>> {
    let mut packages = Map::new();
    for pkg in lock
        .packages
        .iter()
        .filter(|p| p.ecosystem == EcosystemTag::Web)
    {
        let version = require_version(pkg)?;
        let entry = json!({
            "version": version,
            "resolved": pkg.resolved,
            "integrity": pkg.integrity,
        });
        packages.insert(format!("node_modules/{}", pkg.name), entry);
    }

    let doc: Value = json!({
        "lockfileVersion": 3,
        "packages": Value::Object(packages),
    });
    serde_json::to_vec_pretty(&doc)
        .map_err(|e| MgError::Other(format!("package-lock serialization failed: {e}")))
}

/// An exported pin without a version is a broken lock — fail closed.
/// Pin export thiếu version là lock hỏng — fail-closed.
fn require_version(pkg: &crate::schema::Package) -> MgResult<&str> {
    if pkg.version.trim().is_empty() {
        return Err(MgError::InvalidVersion(format!(
            "package '{}' has an empty version; refusing to export a pin without a version",
            pkg.name
        )));
    }
    Ok(&pkg.version)
}

/// Map the canonical registry id to Cargo's `source` URL shape.
/// Ánh xạ registry id canonical sang shape `source` của Cargo.
///
/// "crates://host" → "registry+https://host" (Cargo's registry source
/// convention); anything else passes through unchanged (skeleton scope).
/// "crates://host" → "registry+https://host" (quy ước registry source của
/// Cargo); giá trị khác giữ nguyên (trong phạm vi skeleton).
fn cargo_source_url(registry: &str) -> String {
    match registry.strip_prefix("crates://") {
        Some(rest) => format!("registry+https://{rest}"),
        None => registry.to_string(),
    }
}
