[package]
name = "megagate-core-napi"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/megagate/megagate"

[lib]
name = "megagate_core"
crate-type = ["cdylib"]

[dependencies]
megagate-ffi = { path = "/Users/doanmihh/Documents/Workspace/MegaGate/crates/megagate-ffi" }
napi = { version = "3.9", features = ["napi7", "napi8", "tokio"] }
napi-derive = "3.5"