/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function napiMegagateAdd(projectDir: string, packageSpec: string, dev: boolean): Promise<string>

export declare function napiMegagateInstall(projectDir: string, configJson?: string | undefined | null): Promise<string>

export declare function napiMegagateList(projectDir: string, depth: number): Promise<string>

export declare function napiMegagateLockVerify(projectDir: string, configJson?: string | undefined | null): Promise<string>

export declare function napiMegagateRemove(projectDir: string, packageName: string): Promise<string>

export declare function napiMegagateUpdate(projectDir: string, packageName?: string | undefined | null): Promise<string>
export declare function napiMegagateAdd(projectDir: string, packageSpec: string, dev: boolean): Promise<string>

export declare function napiMegagateInstall(projectDir: string, configJson?: string | undefined | null): Promise<string>

export declare function napiMegagateList(projectDir: string, depth: number): Promise<string>

export declare function napiMegagateLockVerify(projectDir: string, configJson?: string | undefined | null): Promise<string>

export declare function napiMegagateRemove(projectDir: string, packageName: string): Promise<string>

export declare function napiMegagateUpdate(projectDir: string, packageName?: string | undefined | null): Promise<string>
