//! `ai/docker.rs` — Docker & Docker Compose auto-generator for AI Core.

use anyhow::Result;
use std::path::Path;
use crate::commands::optimizer::detect::HardwareInfo;

/// Tự động sinh `Dockerfile` và `docker-compose.yml` tối ưu cho dự án AI dựa theo phần cứng
pub fn generate_ai_docker_files(project_root: &Path) -> Result<()> {
    let hw = HardwareInfo::detect();

    // 1. Sinh Dockerfile với Multi-Stage build tối ưu dung lượng
    let dockerfile_path = project_root.join("Dockerfile");
    if !dockerfile_path.exists() {
        let base_image = if hw.os == "linux" && hw.arch == "x86_64" {
            "nvidia/cuda:12.4.1-runtime-ubuntu22.04"
        } else {
            "python:3.11-slim-bookworm"
        };

        let dockerfile_content = format!(
            "# Generated by MegaGate for AI Core ({:?})\n\
             FROM {base_image} AS base\n\n\
             WORKDIR /app\n\
             ENV PYTHONUNBUFFERED=1 \\\n\
                 PYTHONDONTWRITEBYTECODE=1 \\\n\
                 OMP_NUM_THREADS={} \\\n\
                 MG_AI_ULTRA_COMPRESSION=1\n\n\
             # Install system dependencies\n\
             RUN apt-get update && apt-get install -y --no-install-recommends \\\n\
                 curl build-essential git && \\\n\
                 rm -rf /var/lib/apt/lists/*\n\n\
             # Install Python dependencies\n\
             COPY pyproject.toml ./\n\
             RUN pip install --no-cache-dir --upgrade pip && \\\n\
                 pip install --no-cache-dir torch transformers accelerate safetensors pydantic\n\n\
             # Copy application source & configs\n\
             COPY . .\n\n\
             EXPOSE 5134\n\
             CMD [\"python3\", \"src/agent.py\"]\n",
            hw.profile,
            hw.cpu_cores.max(1)
        );

        std::fs::write(&dockerfile_path, dockerfile_content)?;
        mg_ui::success("Generated: Dockerfile (Multi-stage AI Runtime)");
    }

    // 2. Sinh docker-compose.yml với GPU acceleration và Resource limits
    let compose_path = project_root.join("docker-compose.yml");
    if !compose_path.exists() {
        let memory_limit = (hw.total_memory_gb.saturating_sub(2)).max(2);
        let compose_content = format!(
            "# Generated by MegaGate Docker Engine for AI Core\n\
             services:\n\
               ai-agent:\n\
                 build:\n\
                   context: .\n\
                   dockerfile: Dockerfile\n\
                 container_name: megagate-ai-agent\n\
                 ports:\n\
                   - \"5134:5134\"\n\
                 volumes:\n\
                   - .:/app\n\
                   - ~/.megagate/store/v3/models:/root/.megagate/store/v3/models:ro\n\
                 deploy:\n\
                   resources:\n\
                     limits:\n\
                       cpus: '{:.1}'\n\
                       memory: {}G\n\
                 environment:\n\
                   - OMP_NUM_THREADS={}\n\
                   - TOKENIZERS_PARALLELISM=true\n\
                   - MG_AI_TOKEN_ACTIVATION_PRUNING=1\n",
            (hw.cpu_cores as f64) * 0.9,
            memory_limit,
            hw.cpu_cores.max(1)
        );

        std::fs::write(&compose_path, compose_content)?;
        mg_ui::success("Generated: docker-compose.yml (Resource Limits & Model CAS volume mount)");
    }

    Ok(())
}
