load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_rust//rust:defs.bzl", "rust_library")

# Protobuf definitions
proto_library(
    name = "megagate_proto",
    srcs = glob(["proto/megagate/v1/*.proto"]),
    visibility = ["//visibility:public"],
    deps = [
        "@rules_proto//proto:well_known_protos",
    ],
)

# Generated Rust code
rust_library(
    name = "megagate_proto_rust",
    srcs = [":megagate_proto"],
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "@rules_proto//proto:protobuf_rust",
    ],
)