import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';
import {
    PackageJson,
    LockFile,
    InstallOptions,
    AddOptions,
    UpdateOptions,
    ResolvedDependency,
} from '../types.js';
import {
    loadLock,
    saveLock,
    createEmptyLock,
    lockKey,
    addPackageToLock,
    getImporterDeps,
    updateImporter,
    verifyLockIntegrity,
} from '../lockfile/lock.js';

// NAPI bindings (generated by napi-rs)
import native from '../../napi/index.js';

export interface InstallResult {
    added: string[];
    updated: string[];
    removed: string[];
}

export class RustInstaller {
    private cwd: string;
    private storeDir: string;
    private production: boolean;
    private registry: string;

    constructor(options: InstallOptions = {}) {
        this.cwd = resolve(options.storeDir ? process.cwd() : process.cwd());
        this.storeDir = options.storeDir || '';
        this.production = options.production || false;
        this.registry = options.registry || 'https://registry.npmjs.org';
    }

    private buildConfig(): string {
        return JSON.stringify({
            store_dir: this.storeDir,
            registry: this.registry,
            max_concurrency: 16,
            link_strategy: 'hardlink',
            minimum_release_age_hours: 24,
            approve_builds: true,
            lockdown_mode: false,
            offline_mode: false,
            prefer_offline: false,
        });
    }

    async install(options: InstallOptions = {}): Promise<InstallResult> {
        const config = this.buildConfig();
        const result = await native.napiMegagateInstall(this.cwd, config);
        return JSON.parse(result);
    }

    async add(pkgSpec: string, options: AddOptions = {}): Promise<InstallResult> {
        const config = this.buildConfig();
        const result = await native.napiMegagateAdd(this.cwd, pkgSpec, options.dev || false);
        return JSON.parse(result);
    }

    async update(pkgSpec?: string, options: UpdateOptions = {}): Promise<InstallResult> {
        const config = this.buildConfig();
        const result = await native.napiMegagateUpdate(this.cwd, pkgSpec || null);
        return JSON.parse(result);
    }

    async remove(pkgName: string): Promise<InstallResult> {
        const config = this.buildConfig();
        const result = await native.napiMegagateRemove(this.cwd, pkgName);
        return JSON.parse(result);
    }

    async list(depth = 0): Promise<Record<string, string>> {
        const config = this.buildConfig();
        const result = await native.napiMegagateList(this.cwd, depth);
        return JSON.parse(result);
    }

    async verify(): Promise<{ valid: boolean; errors: string[] }> {
        const config = this.buildConfig();
        const result = await native.napiMegagateLockVerify(this.cwd, config);
        return JSON.parse(result);
    }
}

export function createInstaller(options?: InstallOptions): RustInstaller {
    return new RustInstaller(options);
}