//! `optimizer/generators.rs` — Core-Neutral Optimizer (Runtime Detection + Adapter Pattern)
//! `optimizer/generators.rs` — Bộ sinh cấu hình tối ưu trung lập Core theo runtime và adapter

use super::adapters;
use super::detect::HardwareInfo;
use super::runtime_detect;
use anyhow::Result;
use std::path::Path;

/// Optimized configuration file information — thông tin file cấu hình đã tối ưu
pub struct OptimizedConfigFile {
    /// Relative path from project root — đường dẫn tương đối từ project root
    pub relative_path: String,
    /// Generated file content — nội dung file được tạo
    pub content: String,
    /// Explanation of optimization reason — giải thích lý do tối ưu
    pub description: String,
}

/// Generate optimized configuration files for each Core and actual Hardware specs — sinh các file cấu hình tối ưu phù hợp với từng Core và thông số Hardware thực tế
/// REFACTORED: Runtime detection + adapter pattern (no hardcoding per core) — đã refactor: phát hiện runtime + pattern adapter
pub fn generate_optimizations_for_core(
    core: &str,
    hw: &HardwareInfo,
    project_root: &Path,
) -> Vec<OptimizedConfigFile> {
    let mut files = vec![];

    // 0. Metadata Optimizer Manifest for all Cores — metadata manifest chung cho mọi Core
    files.push(OptimizedConfigFile {
        relative_path: ".mgc-optimizer/profile.json".to_string(),
        content: serde_json::to_string_pretty(hw).unwrap_or_default(),
        description: format!(
            "System hardware snapshot & assigned profile ({:?})",
            hw.profile
        ),
    });

    // 1. Detect runtimes for this project + core — phát hiện runtimes cho project + core này
    let detected_runtimes = runtime_detect::detect_runtimes(project_root, core);

    // 2. Find matching adapters — tìm adapters khớp
    let matched_adapters = adapters::find_adapters(&detected_runtimes);

    // 3. Generate optimizations via adapters — tạo optimizations qua adapters
    for adapter in matched_adapters {
        let adapter_files = adapter.generate(hw);
        mgc_ui::info(&format!(
            "Optimizer: {} runtime detected, generating {} config(s)",
            adapter.name(),
            adapter_files.len()
        ));
        files.extend(adapter_files);
    }

    // 4. Fallback for cloud/cicd cores (container-neutral) — fallback cho cloud/cicd cores
    if matches!(core, "clo" | "cloud" | "cicd") {
        files.push(OptimizedConfigFile {
            relative_path: ".mgc-optimizer/deploy_concurrency.env".to_string(),
            content: format!(
                "# Generated by MagiCore Optimizer for Cloud/CICD Core ({:?})\n\
                 MGC_PARALLEL_UPLOADS={}\n\
                 DOCKER_BUILDKIT=1\n",
                hw.profile,
                hw.cpu_cores.max(2)
            ),
            description: format!(
                "Deploy & container build pipeline concurrency ({})",
                hw.cpu_cores.max(2)
            ),
        });
    }

    files
}

/// Write optimized configuration file with Hash Guard — ghi file cấu hình tối ưu với Hash Guard
pub fn apply_optimized_file(
    project_root: &Path,
    opt_file: &OptimizedConfigFile,
    force: bool,
) -> Result<bool> {
    let target_path = project_root.join(&opt_file.relative_path);

    if target_path.exists() && !force {
        let existing = std::fs::read_to_string(&target_path)?;
        // If JSON or config file without header marker -> check user modifications — nếu JSON hoặc file config không có header marker → kiểm tra sửa đổi user
        if target_path.extension().is_none_or(|ext| ext != "json")
            && !existing.starts_with("# Generated by MagiCore Optimizer")
        {
            mgc_ui::warning(&format!(
                "Skipping {} (modified by user, use --force to overwrite)",
                opt_file.relative_path
            ));
            return Ok(false);
        }
    }

    if let Some(parent) = target_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(&target_path, &opt_file.content)?;
    mgc_ui::success(&format!(
        "Optimized: {} ({})",
        opt_file.relative_path, opt_file.description
    ));
    Ok(true)
}
