//! `optimizer/generators.rs` — File generators per Core with Hash Guard (prevents overwriting user edits).

use super::detect::{HardwareInfo, SystemProfile};
use anyhow::Result;
use std::path::Path;

/// Thông tin 1 file cấu hình được tối ưu
pub struct OptimizedConfigFile {
    /// Đường dẫn tương đối từ project root
    pub relative_path: String,
    /// Nội dung file được tạo
    pub content: String,
    /// Giải thích lý do tối ưu
    pub description: String,
}

/// Sinh các file cấu hình tối ưu phù hợp với từng Core và thông số Hardware thực tế
pub fn generate_optimizations_for_core(core: &str, hw: &HardwareInfo) -> Vec<OptimizedConfigFile> {
    let mut files = vec![];

    // 0. Metadata Optimizer Manifest chung cho mọi Core (quản lý thống nhất trong .mg-optimizer/)
    files.push(OptimizedConfigFile {
        relative_path: ".mg-optimizer/profile.json".to_string(),
        content: serde_json::to_string_pretty(hw).unwrap_or_default(),
        description: format!(
            "System hardware snapshot & assigned profile ({:?})",
            hw.profile
        ),
    });

    // 1. Web Core (Node/V8, Bun, Turbopack, Vite Dev & Build flags)
    if core == "web" {
        let max_old_space = match hw.profile {
            SystemProfile::HighPerformance => 8192,
            SystemProfile::Standard => 4096,
            SystemProfile::Constrained => 2048,
        };
        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/web_env.env".to_string(),
            content: format!(
                "# Generated by MegaGate Optimizer for Web Core ({:?})\n\
                 NODE_OPTIONS=\"--max-old-space-size={max_old_space} --enable-source-maps\"\n\
                 UV_THREADPOOL_SIZE={}\n\
                 VITE_ESBUILD_TARGET=esnext\n\
                 NEXT_TELEMETRY_DISABLED=1\n",
                hw.profile,
                hw.cpu_cores.max(4)
            ),
            description: format!(
                "V8 Heap ({max_old_space}MB) & async I/O worker threads ({})",
                hw.cpu_cores.max(4)
            ),
        });
    }

    // 2. Rust / Native-based Cores (Game, Lib, Iot, App)
    if matches!(core, "game" | "lib" | "app" | "iot") {
        let (opt_level, codegen_units, lto) = match hw.profile {
            SystemProfile::HighPerformance => ("3", "16", "thin"),
            SystemProfile::Standard => ("2", "8", "false"),
            SystemProfile::Constrained => ("1", "4", "false"),
        };
        let lld_flag = if hw.os == "macos" {
            "# Native Apple Clang linker"
        } else {
            "rustflags = [\"-C\", \"linker=clang\", \"-C\", \"link-arg=-fuse-ld=lld\", \"-C\", \"target-cpu=native\"]"
        };

        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/cargo_profile.toml".to_string(),
            content: format!(
                "# Generated by MegaGate Optimizer for {} Core ({:?})\n\
                 [build]\n\
                 jobs = {}\n\
                 {lld_flag}\n\n\
                 [profile.dev]\n\
                 opt-level = {opt_level}\n\
                 codegen-units = {codegen_units}\n\
                 debug = 1\n\n\
                 [profile.release]\n\
                 opt-level = 3\n\
                 lto = \"{lto}\"\n\
                 codegen-units = 1\n\
                 panic = \"abort\"\n",
                core, hw.profile, hw.cpu_cores
            ),
            description: format!(
                "Cargo parallel build jobs ({}) & dev/release profile",
                hw.cpu_cores
            ),
        });
    }

    // 3. AI Core (PyTorch, Token Activation Pruning, KV-Cache Compression, 330B Large Model Sharding)
    if core == "ai" {
        let threads = hw.cpu_cores.max(1);
        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/ai_runtime.env".to_string(),
            content: format!(
                "# Generated by MegaGate Optimizer for AI Core ({:?})\n\
                 OMP_NUM_THREADS={threads}\n\
                 MKL_NUM_THREADS={threads}\n\
                 TORCH_NUM_THREADS={threads}\n\
                 TOKENIZERS_PARALLELISM=true\n\
                 PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512\n\
                 MG_AI_ULTRA_COMPRESSION=1\n\
                 MG_AI_TOKEN_ACTIVATION_PRUNING=1\n\
                 MG_AI_KV_CACHE_COMPRESSION=1\n",
                hw.profile
            ),
            description: format!(
                "AI Ultra-Compression & compute matrix thread pool ({threads} threads)"
            ),
        });

        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/docker_limits.env".to_string(),
            content: format!(
                "# Generated by MegaGate Optimizer for AI Container Limits ({:?})\n\
                 CONTAINER_CPUS={:.1}\n\
                 CONTAINER_MEMORY={}g\n",
                hw.profile,
                (hw.cpu_cores as f64) * 0.9,
                (hw.total_memory_gb.saturating_sub(2)).max(2)
            ),
            description: "Docker CPU/Memory limits based on detected physical RAM".to_string(),
        });

        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/large_model_sharding.json".to_string(),
            content: format!(
                "{{\n\
                  \"target_architecture\": \"ultra-dense-330b\",\n\
                  \"sparse_token_budget\": 4096,\n\
                  \"tensor_parallel_shards\": {},\n\
                  \"pipeline_parallel_stages\": 1,\n\
                  \"cpu_offload\": true\n\
                }}\n",
                (hw.cpu_cores / 4).max(1)
            ),
            description: "Ultra-Large Model (330B/70B) Token Pruning & Sharding Strategy"
                .to_string(),
        });
    }

    // 4. Cloud / CICD Core (Fast container packaging & concurrent upload streams)
    if matches!(core, "clo" | "cloud" | "cicd") {
        files.push(OptimizedConfigFile {
            relative_path: ".mg-optimizer/deploy_concurrency.env".to_string(),
            content: format!(
                "# Generated by MegaGate Optimizer for Cloud/CICD Core ({:?})\n\
                 MG_PARALLEL_UPLOADS={}\n\
                 DOCKER_BUILDKIT=1\n",
                hw.profile,
                hw.cpu_cores.max(2)
            ),
            description: format!(
                "Deploy & container build pipeline concurrency ({})",
                hw.cpu_cores.max(2)
            ),
        });
    }

    files
}

/// Ghi file cấu hình tối ưu với Hash Guard
pub fn apply_optimized_file(
    project_root: &Path,
    opt_file: &OptimizedConfigFile,
    force: bool,
) -> Result<bool> {
    let target_path = project_root.join(&opt_file.relative_path);

    if target_path.exists() && !force {
        let existing = std::fs::read_to_string(&target_path)?;
        // Nếu file JSON hoặc file cấu hình không có header marker -> kiểm tra user modifications
        if target_path.extension().is_none_or(|ext| ext != "json")
            && !existing.starts_with("# Generated by MegaGate Optimizer")
        {
            mg_ui::warning(&format!(
                "Skipping {} (modified by user, use --force to overwrite)",
                opt_file.relative_path
            ));
            return Ok(false);
        }
    }

    if let Some(parent) = target_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(&target_path, &opt_file.content)?;
    mg_ui::success(&format!(
        "Optimized: {} ({})",
        opt_file.relative_path, opt_file.description
    ));
    Ok(true)
}
