//! PyPI native engine (Python).
//! Engine native PyPI (Python).
//!
//! JSON API spec: `{index}/pypi/{name}/json` lists `info` + `releases`
//! (version → files). Transitive deps come from the version-specific
//! `{index}/pypi/{name}/{version}/json` → `info.requires_dist` (PEP 508).
//! Wheel selection prefers a universal `py3-none-any` wheel, then a
//! host-platform wheel, then an sdist. sha256 is verified from `digests`.
//! Spec JSON API: `{index}/pypi/{name}/json` liệt kê `info` + `releases`
//! (version → files). Dep bắc cầu lấy từ `{index}/pypi/{name}/{version}/json`
//! → `info.requires_dist` (PEP 508). Chọn wheel ưu tiên wheel phổ quát
//! `py3-none-any`, rồi wheel khớp platform host, rồi sdist. sha256 xác minh
//! từ `digests`.

use super::{RegistryProtocol, ResolvedEntry};
use async_trait::async_trait;
use mgc_types::{MgError, MgResult, Version};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

const DEFAULT_INDEX_URL: &str = "https://pypi.org";

/// Native PyPI engine.
/// Engine native PyPI.
#[derive(Debug, Clone)]
pub struct PypiProtocol {
    index_url: String,
    client: reqwest::Client,
}

impl PypiProtocol {
    /// Build with an explicit index URL.
    /// Dựng với index URL tường minh.
    pub fn new(index_url: &str) -> Self {
        Self {
            index_url: index_url.trim_end_matches('/').to_string(),
            client: reqwest::Client::new(),
        }
    }

    /// Build from environment: `MGC_PYPI_INDEX_URL`.
    /// Dựng từ môi trường: `MGC_PYPI_INDEX_URL`.
    pub fn from_env() -> Self {
        let index_url = std::env::var("MGC_PYPI_INDEX_URL")
            .ok()
            .filter(|v| !v.is_empty())
            .unwrap_or_else(|| DEFAULT_INDEX_URL.to_string());
        Self::new(&index_url)
    }

    async fn get_text(&self, url: &str) -> MgResult<String> {
        let resp = self
            .client
            .get(url)
            .send()
            .await
            .map_err(|e| MgError::Network(format!("GET {url} failed: {e}")))?;
        let status = resp.status();
        let body = resp
            .text()
            .await
            .map_err(|e| MgError::Network(format!("read {url} body failed: {e}")))?;
        if !status.is_success() {
            return Err(MgError::Network(format!(
                "GET {url} returned {status}: {body}"
            )));
        }
        Ok(body)
    }

    /// Materialize a wheel/sdist into `{wheels_dir}/<filename>`.
    /// Materialize wheel/sdist vào `{wheels_dir}/<filename>`.
    pub fn materialize(
        &self,
        entry: &ResolvedEntry,
        bytes: &[u8],
        wheels_dir: &Path,
    ) -> MgResult<PathBuf> {
        std::fs::create_dir_all(wheels_dir)?;
        let filename = entry
            .artifact_url
            .rsplit('/')
            .next()
            .filter(|s| !s.is_empty())
            .unwrap_or("artifact");
        let dest = wheels_dir.join(filename);
        std::fs::write(&dest, bytes)?;
        Ok(dest)
    }

    /// Export a `requirements.lock` (`--require-hashes`) body for offline
    /// `pip install -r` — pinned, hash-carrying, no re-resolve.
    /// Xuất body `requirements.lock` (`--require-hashes`) cho `pip install -r`
    /// offline — ghim, mang hash, không resolve lại.
    pub fn requirements_lock(entries: &[ResolvedEntry]) -> String {
        let mut out = String::from("# Generated by MagiCore (native PyPI resolve).\n");
        for entry in entries {
            if entry.sha256.is_empty() {
                out.push_str(&format!("{}=={}\n", entry.name, entry.version));
            } else {
                out.push_str(&format!(
                    "{}=={} --hash=sha256:{}\n",
                    entry.name, entry.version, entry.sha256
                ));
            }
        }
        out
    }
}

impl Default for PypiProtocol {
    fn default() -> Self {
        Self::from_env()
    }
}

#[async_trait]
impl RegistryProtocol for PypiProtocol {
    async fn resolve(&self, name: &str, range: &str) -> MgResult<ResolvedEntry> {
        let url = format!("{}/pypi/{name}/json", self.index_url);
        let body = self.get_text(&url).await?;
        let doc: PypiJson = serde_json::from_str(&body)
            .map_err(|e| MgError::Other(format!("parse pypi json failed: {e}")))?;

        let mut best: Option<(Version, Vec<PypiFile>)> = None;
        for (ver_str, files) in &doc.releases {
            // Empty file list = yanked/empty release → skip.
            // (Danh sách file rỗng = release yanked/trống → bỏ.)
            if files.is_empty() {
                continue;
            }
            let Ok(version) = Version::parse(ver_str) else {
                continue;
            };
            if !pep440_matches(range, &version) {
                continue;
            }
            if best.as_ref().is_none_or(|(v, _)| version > *v) {
                best = Some((version, files.clone()));
            }
        }

        let (version, files) =
            best.ok_or_else(|| MgError::Other(format!("no version of {name} matches '{range}'")))?;
        let file = select_file(&files)
            .ok_or_else(|| MgError::Other(format!("no downloadable file for {name} {version}")))?;

        let mut markers = Vec::new();
        if file.packagetype == "bdist_wheel" {
            let (py, abi, plat) = wheel_tags(&file.filename);
            markers.push(format!("wheel:{py}-{abi}-{plat}"));
        } else {
            markers.push(format!("sdist:{}", file.filename));
        }
        if let Some(rp) = &file.requires_python {
            markers.push(format!("requires-python:{rp}"));
        }

        // Transitive deps: version-specific JSON carries the real requires_dist.
        // (Dep bắc cầu: JSON theo version mang requires_dist thật.)
        let version_url = format!("{}/pypi/{name}/{version}/json", self.index_url);
        let version_body = self.get_text(&version_url).await?;
        let version_doc: PypiJson = serde_json::from_str(&version_body)
            .map_err(|e| MgError::Other(format!("parse pypi version json failed: {e}")))?;

        let mut deps = Vec::new();
        if let Some(requires) = version_doc.info.requires_dist {
            for spec in requires {
                let Some((dep_name, dep_range, marker)) = parse_pep508(&spec) else {
                    continue;
                };
                if marker.as_deref().is_some_and(|m| m.contains("extra")) {
                    markers.push(format!("marker:{}", marker.unwrap_or_default()));
                    continue;
                }
                if let Some(m) = marker {
                    markers.push(format!("marker:{m}"));
                }
                deps.push((dep_name, dep_range));
            }
        }

        Ok(ResolvedEntry {
            name: name.to_string(),
            version: version.to_string(),
            deps,
            artifact_url: file.url.clone(),
            sha256: file.digests.sha256.clone(),
            extra_markers: markers,
        })
    }

    async fn download(&self, entry: &ResolvedEntry) -> MgResult<Vec<u8>> {
        let resp = self
            .client
            .get(&entry.artifact_url)
            .send()
            .await
            .map_err(|e| MgError::Network(format!("GET {} failed: {e}", entry.artifact_url)))?;
        let status = resp.status();
        let bytes = resp.bytes().await.map_err(|e| {
            MgError::Network(format!("read {} body failed: {e}", entry.artifact_url))
        })?;
        if !status.is_success() {
            return Err(MgError::Network(format!(
                "GET {} returned {status}",
                entry.artifact_url
            )));
        }
        Ok(bytes.to_vec())
    }
}

/// Select the best installable file: universal wheel → host wheel →
/// sdist. There is deliberately NO "any wheel" fallback: installing a
/// wheel built for another platform is a silent wrong-artifact install
/// (V1.2: fail-closed — no file at all beats the wrong file).
/// Chọn file cài tốt nhất: wheel phổ quát → wheel host → sdist. Cố ý
/// KHÔNG fallback "wheel bất kỳ".
fn select_file(files: &[PypiFile]) -> Option<&PypiFile> {
    if let Some(f) = files.iter().find(|f| is_universal_wheel(f)) {
        return Some(f);
    }
    if let Some(f) = files
        .iter()
        .find(|f| f.packagetype == "bdist_wheel" && wheel_platform_matches_host(&f.filename))
    {
        return Some(f);
    }
    files.iter().find(|f| f.packagetype == "sdist")
}

fn is_universal_wheel(file: &PypiFile) -> bool {
    if file.packagetype != "bdist_wheel" {
        return false;
    }
    let (py, abi, plat) = wheel_tags(&file.filename);
    abi == "none" && plat == "any" && py.contains("py3")
}

/// Parse a wheel filename into `(python, abi, platform)` tags (last 3 parts).
/// Parse filename wheel thành tag `(python, abi, platform)` (3 phần cuối).
fn wheel_tags(filename: &str) -> (String, String, String) {
    let stem = filename.strip_suffix(".whl").unwrap_or(filename);
    let parts: Vec<&str> = stem.split('-').collect();
    if parts.len() >= 3 {
        let n = parts.len();
        (
            parts[n - 3].to_string(),
            parts[n - 2].to_string(),
            parts[n - 1].to_string(),
        )
    } else {
        (String::new(), String::new(), String::new())
    }
}

fn wheel_platform_matches_host(filename: &str) -> bool {
    let (_, _, plat) = wheel_tags(filename);
    let os = std::env::consts::OS;
    let arch = std::env::consts::ARCH;
    if os == "macos" && arch == "aarch64" {
        return plat.starts_with("macosx_")
            && (plat.ends_with("_arm64") || plat.ends_with("_universal2"));
    }
    if os == "linux" && arch == "aarch64" {
        return (plat.starts_with("manylinux_")
            || plat.starts_with("musllinux_")
            || plat.starts_with("linux_"))
            && plat.ends_with("_aarch64");
    }
    false
}

/// PEP 440 subset matcher: `==`, `==x.y.*`, `>=`, `<=`, `>`, `<`, `!=`,
/// `~=` (compatible release), comma = AND, bare version = exact.
/// Matcher PEP 440 subset: `==`, `==x.y.*`, `>=`, `<=`, `>`, `<`, `!=`,
/// `~=` (compatible release), phẩy = AND, version trần = exact.
fn pep440_matches(range: &str, version: &Version) -> bool {
    let range = range.trim();
    if range.is_empty() || range == "*" {
        return true;
    }
    range
        .split(',')
        .map(str::trim)
        .all(|part| pep440_part(part, version))
}

fn pep440_part(part: &str, version: &Version) -> bool {
    let part = part.trim();
    if part == "*" {
        return true;
    }
    if let Some(p) = part.strip_prefix("==") {
        return pep_eq(p, version);
    }
    if let Some(p) = part.strip_prefix("~=") {
        return pep_compat(p, version);
    }
    if let Some(p) = part.strip_prefix("!=") {
        return !pep_eq(p, version);
    }
    if let Some(p) = part.strip_prefix(">=") {
        return pep_ge(p, version);
    }
    if let Some(p) = part.strip_prefix("<=") {
        return pep_le(p, version);
    }
    if let Some(p) = part.strip_prefix('>') {
        return pep_gt(p, version);
    }
    if let Some(p) = part.strip_prefix('<') {
        return pep_lt(p, version);
    }
    // bare version → exact.
    pep_eq(part, version)
}

fn pep_eq(raw: &str, version: &Version) -> bool {
    let raw = raw.trim();
    if let Some(base) = raw.strip_suffix(".*") {
        let base = base.trim_end_matches('.');
        let parts: Vec<&str> = base.split('.').collect();
        if parts.is_empty() {
            return true;
        }
        let major: u64 = parts[0].parse().unwrap_or(u64::MAX);
        if version.major != major {
            return false;
        }
        if let Some(minor) = parts.get(1) {
            let minor: u64 = minor.parse().unwrap_or(u64::MAX);
            return version.minor == minor;
        }
        true
    } else {
        Version::parse(raw)
            .map(|target| version == &target)
            .unwrap_or(false)
    }
}

fn pep_compat(raw: &str, version: &Version) -> bool {
    let raw = raw.trim();
    let Some(target) = Version::parse(raw).ok() else {
        return false;
    };
    if version < &target {
        return false;
    }
    let parts: Vec<&str> = raw.split('.').collect();
    if parts.len() <= 2 {
        // ~=1.4 → >=1.4,<2.0
        version.major == target.major
    } else {
        // ~=1.4.5 → >=1.4.5,<1.5
        version.major == target.major && version.minor == target.minor
    }
}

fn pep_ge(raw: &str, version: &Version) -> bool {
    Version::parse(raw.trim())
        .map(|t| version >= &t)
        .unwrap_or(false)
}
fn pep_le(raw: &str, version: &Version) -> bool {
    Version::parse(raw.trim())
        .map(|t| version <= &t)
        .unwrap_or(false)
}
fn pep_gt(raw: &str, version: &Version) -> bool {
    Version::parse(raw.trim())
        .map(|t| version > &t)
        .unwrap_or(false)
}
fn pep_lt(raw: &str, version: &Version) -> bool {
    Version::parse(raw.trim())
        .map(|t| version < &t)
        .unwrap_or(false)
}

/// Parse a PEP 508 requirement into `(name, range, marker)`. Extra deps are
/// surfaced via the marker (caller skips them); `[extras]` are dropped.
/// Parse requirement PEP 508 thành `(name, range, marker)`. Dep extra lộ qua
/// marker (caller bỏ); `[extras]` bị loại.
fn parse_pep508(spec: &str) -> Option<(String, String, Option<String>)> {
    let spec = spec.trim();
    if spec.is_empty() {
        return None;
    }
    let (req, marker) = match spec.split_once(';') {
        Some((r, m)) => (r.trim(), Some(m.trim().to_string())),
        None => (spec.trim(), None),
    };
    let op_idx = req
        .find(|c: char| ['=', '>', '<', '!', '~'].contains(&c))
        .unwrap_or(req.len());
    let name_part = req[..op_idx].split('[').next().unwrap_or("").trim();
    if name_part.is_empty() {
        return None;
    }
    let range = if op_idx < req.len() {
        req[op_idx..].trim().to_string()
    } else {
        "*".to_string()
    };
    Some((name_part.to_string(), range, marker))
}

#[derive(Debug, Deserialize)]
struct PypiJson {
    #[serde(default)]
    info: PypiInfo,
    #[serde(default)]
    releases: HashMap<String, Vec<PypiFile>>,
}

#[derive(Debug, Deserialize, Default)]
struct PypiInfo {
    #[serde(default)]
    requires_dist: Option<Vec<String>>,
}

#[derive(Debug, Clone, Deserialize)]
struct PypiFile {
    #[serde(default)]
    filename: String,
    #[serde(default)]
    url: String,
    #[serde(default)]
    digests: PypiDigests,
    #[serde(default)]
    packagetype: String,
    #[serde(default)]
    requires_python: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
struct PypiDigests {
    #[serde(default)]
    sha256: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use mgc_types::Version;

    #[test]
    fn pep440_compatible_release() {
        let v = Version::parse("1.4.2").unwrap();
        assert!(pep440_matches("~=1.4", &v));
        assert!(!pep440_matches("~=1.4", &Version::parse("2.0.0").unwrap()));
        assert!(pep440_matches("~=1.4.5", &Version::parse("1.4.9").unwrap()));
        assert!(!pep440_matches(
            "~=1.4.5",
            &Version::parse("1.5.0").unwrap()
        ));
    }

    #[test]
    fn pep440_eq_wildcard() {
        assert!(pep440_matches("==1.2.*", &Version::parse("1.2.9").unwrap()));
        assert!(!pep440_matches(
            "==1.2.*",
            &Version::parse("1.3.0").unwrap()
        ));
        assert!(pep440_matches("!=1.2", &Version::parse("1.3.0").unwrap()));
        assert!(!pep440_matches("!=1.2", &Version::parse("1.2.0").unwrap()));
    }

    #[test]
    fn pep508_parsing() {
        let (name, range, marker) = parse_pep508("requests>=2.0 ; extra == \"security\"").unwrap();
        assert_eq!(name, "requests");
        assert_eq!(range, ">=2.0");
        assert!(marker.unwrap().contains("extra"));
        let (name, range, marker) = parse_pep508("idna").unwrap();
        assert_eq!(name, "idna");
        assert_eq!(range, "*");
        assert!(marker.is_none());
    }

    #[test]
    fn wheel_tags_last_three() {
        assert_eq!(
            wheel_tags("numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl"),
            (
                "cp312".to_string(),
                "cp312".to_string(),
                "macosx_11_0_arm64".to_string()
            )
        );
        assert_eq!(
            wheel_tags("pkg-1.0-py3-none-any.whl"),
            ("py3".to_string(), "none".to_string(), "any".to_string())
        );
    }
}
