syntax = "proto3";

package megagate.v1;

option go_package = "github.com/megagate/megagate/gen/go/megagate/v1;v1";
option java_package = "dev.megagate.v1";
option java_multiple_files = true;
option csharp_namespace = "Megagate.V1";

import "common.proto";
import "package.proto";

message ExtractRequest {
    PackageRef package_ref = 1;
    bytes tarball_data = 2;
}

message ExtractResponse {
    bool success = 1;
    string integrity = 2;
    uint64 size = 3;
    string error = 4;
}

message IntegrityInfo {
    string integrity = 1;
    uint64 size = 2;
}

message VerifyIntegrityRequest {
    PackageRef package_ref = 1;
    string expected_integrity = 2;
}

message VerifyIntegrityResponse {
    bool valid = 1;
    string actual_integrity = 2;
}
