use anyhow::Result;
use clap::{Parser, Subcommand};

mod adapters;
mod commands;
mod core;
mod ui; // UI lives in src/ui/mod.rs

use ui::run_ui;

#[derive(Parser)]
#[command(name = "megagate")]
#[command(author = "Generated by OpenCode")]
#[command(version = env!("CARGO_PKG_VERSION"))]
#[command(about = "Multi-platform package manager core")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Ui, // launch interactive UI
    Install {
        target: Option<String>,
    },
    Update {
        package: Option<String>,
    },
    Remove {
        package: String,
    },
    List {
        #[arg(short, long)]
        graph: bool,
    },
    Audit,
    Export {
        format: String,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();
    let cli = Cli::parse();
    match cli.command {
        Commands::Install { target } => commands::install(target).await?,
        Commands::Update { package } => commands::update(package).await?,
        Commands::Remove { package } => commands::remove(package).await?,
        Commands::List { graph } => commands::list(graph).await?,
        Commands::Audit => commands::audit().await?,
        Commands::Export { format } => commands::export(format).await?,

        Commands::Ui => {
            let cwd = std::env::current_dir()?;
            run_ui(cwd).await?
        }
    }
    Ok(())
}
