[[files]]
source = "go.mod"
required_context = ["project_slug"]
target = "go.mod"

[[files]]
source = "main.go"
required_context = ["project_name"]
target = "cmd/server/main.go"

[[files]]
source = "Dockerfile"
target = "Dockerfile"
include_features = ["docker"]

[[files]]
source = ".dockerignore"
target = ".dockerignore"
include_features = ["docker"]
